- type: startingGear
  id: SyndicateLoneOperativeGearFullRoundStart
  parent: SyndicateLoneOperativeGearFull
  storage:
    back:
    - NukeOpsDeclarationOfWar

- type: antagSpecifier
  parent: LoneOp
  id: LoneOpRoundStart
  startingGear: SyndicateLoneOperativeGearFullRoundStart
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateElite
    nameFormat: name-format-nukie-commander
  mindRoles:
  - MindRoleNukeops
