using System.Linq;
using System.Numerics;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.EntitySearch;

[GenerateTypedNameReferences]
public sealed partial class EntitySearchWindow : DefaultWindow
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IClientConsoleHost _console = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IClipboardManager _clipboard = default!;
    [Dependency] private IResourceCache _resCache = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPlayerManager _playerMan = default!;

    public event Action? SearchRequested;
    public event Action? NextResultsRequested;

    private int _loadedCount;
    private TimeSpan _searchCooldownEnd = TimeSpan.Zero;

    private readonly Popup _gridFilterPopup;
    private readonly CheckBox _gridFilterEnabled;
    private readonly LineEdit _gridFilterEdit;

    private readonly PinnedEntitiesUIController _pins;

    public EntitySearchWindow(IDependencyCollection deps)
    {
        RobustXamlLoader.Load(this);
        deps.InjectDependencies(this);

        SearchButton.OnPressed += _ => TrySearch();
        SearchLineEdit.OnTextEntered += _ => TrySearch();
        NextButton.OnPressed += _ => NextResultsRequested?.Invoke();

        _gridFilterEnabled = new CheckBox { Text = _loc.GetString("admin-entity-search-grid-toggle") };
        _gridFilterEdit = new LineEdit
        {
            PlaceHolder = _loc.GetString("admin-entity-search-grid-placeholder"),
            HorizontalExpand = true,
        };
        var appendButton = new Button { Text = _loc.GetString("admin-entity-search-grid-append") };
        appendButton.OnPressed += _ => AppendCurrentGrid();

        var menu = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, MinWidth = 300 };
        menu.AddChild(_gridFilterEnabled);
        menu.AddChild(_gridFilterEdit);
        menu.AddChild(appendButton);
        var panel = new PanelContainer();
        panel.AddChild(menu);
        _gridFilterPopup = new Popup();
        _gridFilterPopup.AddChild(panel);
        UserInterfaceManager.ModalRoot.AddChild(_gridFilterPopup);

        GridFilterButton.OnPressed += _ => OpenGridFilter();

        _pins = UserInterfaceManager.GetUIController<PinnedEntitiesUIController>();
        _pins.Changed += RefreshPinned;

        OnClose += () =>
        {
            _gridFilterPopup.Close();
            _gridFilterPopup.Orphan();
            _pins.Changed -= RefreshPinned;
        };

        AdminEntityResultsList.PopulateHeader(HeaderRow, _loc);
        RefreshPinned();
    }

    private void RefreshPinned()
    {
        PinnedList.RemoveAllChildren();
        var pinned = _pins.Pinned.ToArray();
        PinnedSection.Visible = pinned.Length > 0;
        AdminEntityResultsList.Append(PinnedList, pinned, _console, _loc, _clipboard, _resCache, allowDelete: true, pins: _pins);
    }

    public string SearchText => SearchLineEdit.Text;

    public bool GridFilterEnabled => _gridFilterEnabled.Pressed;

    public string GridFilter => _gridFilterEdit.Text;

    private void OpenGridFilter()
    {
        var below = GridFilterButton.GlobalPosition + new Vector2(0, GridFilterButton.Height);
        _gridFilterPopup.Open(UIBox2.FromDimensions(below, new Vector2(300, 0)));
    }

    private void AppendCurrentGrid()
    {
        if (_playerMan.LocalEntity is not { } player)
            return;

        var coords = _entMan.System<SharedTransformSystem>().GetMapCoordinates(player);
        if (!_entMan.System<SharedMapSystem>().TryFindGridAt(coords, out var gridUid, out _))
            return;

        var id = _entMan.GetNetEntity(gridUid).Id.ToString();
        _gridFilterEdit.Text = string.IsNullOrWhiteSpace(_gridFilterEdit.Text)
            ? id
            : $"{_gridFilterEdit.Text},{id}";

        // Appending a grid is affirmative action
        _gridFilterEnabled.Pressed = true;
    }

    public void FocusSearch()
    {
        SearchLineEdit.GrabKeyboardFocus();
    }

    public void SetResults((string name, string? proto, NetEntity entity)[] entities, bool hasNext, int total)
    {
        _loadedCount = entities.Length;
        AdminEntityResultsList.Populate(ItemList, StatusLabel, entities, _console, _loc, _clipboard, _resCache, hasNext, total, allowDelete: true, pins: _pins);
        NextButton.Disabled = !hasNext;
    }

    public void AddResults((string name, string? proto, NetEntity entity)[] entities, bool hasNext, int total)
    {
        _loadedCount += entities.Length;
        AdminEntityResultsList.Append(ItemList, entities, _console, _loc, _clipboard, _resCache, allowDelete: true, pins: _pins);
        AdminEntityResultsList.UpdateStatus(StatusLabel, _loadedCount, hasNext, _loc, total);
        NextButton.Disabled = !hasNext;
    }

    public void BeginNextResultsRequest()
    {
        NextButton.Disabled = true;
    }

    private void TrySearch()
    {
        if (_timing.CurTime < _searchCooldownEnd)
            return;

        if (string.IsNullOrWhiteSpace(SearchLineEdit.Text))
        {
            ItemList.RemoveAllChildren();
            _loadedCount = 0;
            NextButton.Disabled = true;
            StatusLabel.Text = _loc.GetString("admin-entity-search-empty");
            return;
        }

        _searchCooldownEnd = _timing.CurTime + EntitySearchEuiMsg.SearchCooldown;
        UpdateSearchButton();
        SearchRequested?.Invoke();
    }

    private void UpdateSearchButton()
    {
        SearchButton.Disabled = _timing.CurTime < _searchCooldownEnd;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSearchButton();
    }
}
