using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.EntitySearch;

[GenerateTypedNameReferences]
public sealed partial class EntitySearchWindow : DefaultWindow
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IClientConsoleHost _console = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IClipboardManager _clipboard = default!;
    [Dependency] private IResourceCache _resCache = default!;

    public event Action? SearchRequested;
    public event Action? NextResultsRequested;

    private int _loadedCount;
    private TimeSpan _searchCooldownEnd = TimeSpan.Zero;

    public EntitySearchWindow(IDependencyCollection deps)
    {
        RobustXamlLoader.Load(this);
        deps.InjectDependencies(this);

        SearchButton.OnPressed += _ => TrySearch();
        SearchLineEdit.OnTextEntered += _ => TrySearch();
        NextButton.OnPressed += _ => NextResultsRequested?.Invoke();

        AdminEntityResultsList.PopulateHeader(HeaderRow, _loc);
    }

    public string SearchText => SearchLineEdit.Text;

    public void FocusSearch()
    {
        SearchLineEdit.GrabKeyboardFocus();
    }

    public void SetResults((string name, string? proto, NetEntity entity)[] entities, bool hasNext, int total)
    {
        _loadedCount = entities.Length;
        AdminEntityResultsList.Populate(ItemList, StatusLabel, entities, _console, _loc, _clipboard, _resCache, hasNext, total);
        NextButton.Disabled = !hasNext;
    }

    public void AddResults((string name, string? proto, NetEntity entity)[] entities, bool hasNext, int total)
    {
        _loadedCount += entities.Length;
        AdminEntityResultsList.Append(ItemList, entities, _console, _loc, _clipboard, _resCache);
        AdminEntityResultsList.UpdateStatus(StatusLabel, _loadedCount, hasNext, _loc, total);
        NextButton.Disabled = !hasNext;
    }

    public void BeginNextResultsRequest()
    {
        NextButton.Disabled = true;
    }

    private void TrySearch()
    {
        if (_timing.CurTime < _searchCooldownEnd)
            return;

        if (string.IsNullOrWhiteSpace(SearchLineEdit.Text))
        {
            StatusLabel.Text = _loc.GetString("admin-entity-search-empty");
            return;
        }

        _searchCooldownEnd = _timing.CurTime + EntitySearchEuiMsg.SearchCooldown;
        UpdateSearchButton();
        SearchRequested?.Invoke();
    }

    private void UpdateSearchButton()
    {
        SearchButton.Disabled = _timing.CurTime < _searchCooldownEnd;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSearchButton();
    }
}
