using Content.Client._Shitmed.Choice.UI;
using Content.Shared._Shitmed.Medical.Surgery;
using Content.Shared.DoAfter;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Shitmed.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryStepButton : ChoiceControl
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IGameTiming _timing = default!;

    public EntityUid Step { get; set; }

    /// <summary>
    /// Prototype of the surgery this step belongs to and of the step itself, set by
    /// SurgeryBui.AddStep. Used to match this button against an in-progress DoAfter so its
    /// fill can track that DoAfter's live progress - see <see cref="FrameUpdate"/>.
    /// </summary>
    public EntProtoId? SurgeryId { get; set; }
    public EntProtoId? StepId { get; set; }

    public readonly SurgeryStepProgressFill ProgressFill;

    public SurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ProgressFill = new SurgeryStepProgressFill();
        Button.AddChild(ProgressFill);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (SurgeryId == null
            || StepId == null
            || _player.LocalEntity is not { } local
            || !_entities.TryGetComponent(local, out DoAfterComponent? doAfterComp))
        {
            ProgressFill.Visible = false;
            return;
        }

        Content.Shared.DoAfter.DoAfter? active = null;
        foreach (var doAfter in doAfterComp.DoAfters.Values)
        {
            if (doAfter.Cancelled || doAfter.Args.Event is not SurgeryDoAfterEvent surgeryEvent)
                continue;

            if (surgeryEvent.Surgery != SurgeryId.Value || surgeryEvent.Step != StepId.Value)
                continue;

            active = doAfter;
            break;
        }

        if (active == null)
        {
            ProgressFill.Visible = false;
            return;
        }

        var elapsed = _timing.CurTime - active.StartTime;
        var totalSeconds = active.Args.Delay.TotalSeconds;
        var ratio = totalSeconds > 0
            ? Math.Clamp((float)(elapsed.TotalSeconds / totalSeconds), 0f, 1f)
            : 1f;

        ProgressFill.Progress = ratio;
        ProgressFill.Visible = true;
    }
}
