using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Polonium.NewLife;

[GenerateTypedNameReferences]
public sealed partial class NewLifeWindow : FancyWindow
{
    [Dependency] private ILocalizationManager _loc = default!;

    public event Action? Confirmed;

    public NewLifeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        IntroLabel.SetMarkup(_loc.GetString("new-life-window-intro"));

        for (var i = 1; _loc.TryGetString($"new-life-window-rule-{i}", out var rule); i++)
        {
            RulesContainer.AddChild(MakeRule(i, rule));
        }

        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ =>
        {
            Confirmed?.Invoke();
            Close();
        };
    }

    public void SetAvailable(bool available)
    {
        ConfirmButton.Disabled = !available;
    }

    public void SetLivesLeft(int? livesLeft)
    {
        FooterLabel.Text = livesLeft is { } left
            ? _loc.GetString("new-life-window-footer", ("count", left))
            : _loc.GetString("new-life-window-footer-unlimited");
    }

    private static Control MakeRule(int number, string text)
    {
        var numberLabel = new RichTextLabel
        {
            MinWidth = 20,
            VerticalAlignment = VAlignment.Top,
            Margin = new Thickness(0, 0, 4, 0),
        };
        numberLabel.SetMarkup($"[bold]{number}.[/bold]");

        var label = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Top,
        };
        label.SetMarkup(text);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 6),
        };
        row.AddChild(numberLabel);
        row.AddChild(label);
        return row;
    }
}
