using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Polonium.NewLife;

/// <summary>
/// Shown in the lobby when a player who took a new life tries to join as the character they just left.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NewLifeSameCharacterWindow : FancyWindow
{
    public event Action? Confirmed;

    public NewLifeSameCharacterWindow(string characterName)
    {
        RobustXamlLoader.Load(this);

        WarningLabel.SetMarkup(Loc.GetString("new-life-same-character-text",
            ("name", FormattedMessage.EscapeText(characterName))));

        CancelButton.OnPressed += _ => Close();
        ContinueButton.OnPressed += _ =>
        {
            Confirmed?.Invoke();
            Close();
        };
    }
}
