project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /Resources/Locale/en-US/**/*.ftl
    ignore:
      - /Resources/Locale/en-US/**/datasets
      - /Resources/Locale/en-US/**/accent
      - /Resources/Locale/en-US/_Polonium
      - /Resources/Locale/en-US/chat
      - /Resources/Locale/en-US/speech
      - /Resources/Locale/en-US/_Corvax/StationGoal
    translation: /Resources/Locale//%locale%/**//%original_file_name%
    update_option: update_without_changes
