files:
  - source: /Resources/Locale/en-US/**/*.ftl
    ignore:
      - /Resources/Locale/en-US/**/datasets
      - /Resources/Locale/en-US/**/accent
      - /Resources/Locale/en-US/_Polonium
      - /Resources/Locale/en-US/_Corvax
      - /Resources/Locale/en-US/_Imperial
      - /Resources/Locale/en-US/robust-toolbox
      - /Resources/Locale/en-US/_directions.ftl
      - /Resources/Locale/en-US/_units.ftl
      - /Resources/Locale/en-US/_lib.ftl
      - /Resources/Locale/en-US/**/_polonium
      - /Resources/Locale/en-US/**/_corvax
      - /Resources/Locale/en-US/**/_imperial
    translation: /Resources/Locale//%locale%/**//%original_file_name%
    update_option: update_without_changes
