// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 chromiumboy <50505512+chromiumboy@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
// SPDX-FileCopyrightText: 2025 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Popups;
using Content.Shared.RCD;
using Content.Shared.RCD.Components;
using Content.Shared.RCD.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.RCD;

[GenerateTypedNameReferences]
public sealed partial class RCDMenu : RadialMenu
{
    [Dependency] private EntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    private SharedPopupSystem _popup;
    private SpriteSystem _sprites;
    private RCDSystem _rcd;

    public event Action<ProtoId<RCDPrototype>>? SendRCDSystemMessageAction;

    private EntityUid _owner;

    public RCDMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _popup = _entManager.System<SharedPopupSystem>();
        _sprites = _entManager.System<SpriteSystem>();
        _rcd = _entManager.System<RCDSystem>();

        OnChildAdded += AddRCDMenuButtonOnClickActions;
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
        Refresh();
    }

    public void Refresh()
    {
        // Find the main radial container
        var main = FindControl<RadialContainer>("Main");

        // Populate secondary radial containers
        if (!_entManager.TryGetComponent<RCDComponent>(_owner, out var rcd))
            return;

        // Order recipes by their MenuOrder so buttons appear in a stable, designed order
        // within each category (AvailablePrototypes is a HashSet, so its order is otherwise arbitrary).
        var orderedPrototypes = rcd.AvailablePrototypes.OrderBy(id =>
            _protoManager.TryIndex(id, out var p) ? p.MenuOrder ?? int.MaxValue : int.MaxValue);

        foreach (var protoId in orderedPrototypes)
        {
            if (!_protoManager.TryIndex(protoId, out var proto))
                continue;

            if (proto.Mode == RcdMode.Invalid)
                continue;

            var parent = FindControl<RadialContainer>(proto.Category);
            var tooltip = _rcd.GetPrototypeName(proto);
            tooltip = OopsConcat(char.ToUpper(tooltip[0]).ToString(), tooltip.Remove(0, 1));

            var button = new RCDMenuButton()
            {
                SetSize = new Vector2(64f, 64f),
                ToolTip = tooltip,
                ProtoId = protoId,
            };

            // Polonium: render the built entity's full (multi-layer) sprite so pumps/vents/alarms show all
            // their layers - pipe underlay, device body, indicator lights - from the entity's own (upstream)
            // textures, rather than a single RSI state. Falls back to the prototype's Sprite for modes with
            // no representative entity (deconstruct, tile construction).
            Control? icon = null;

            if (proto.Mode == RcdMode.ConstructObject && proto.Prototype != null)
            {
                var view = new EntityPrototypeView()
                {
                    SetSize = new Vector2(64f, 64f),
                    Stretch = SpriteView.StretchMode.Fill,
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                };
                view.SetPrototype(proto.Prototype);
                icon = view;
            }
            else if (proto.Sprite != null)
            {
                icon = new TextureRect()
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = _sprites.Frame0(proto.Sprite),
                    TextureScale = new Vector2(2f, 2f),
                };
            }

            if (icon != null)
                button.AddChild(icon);

            parent.AddChild(button);

            // Ensure that the button that transitions the menu to the associated category layer
            // is visible in the main radial container (as these all start with Visible = false)
            foreach (var child in main.Children)
            {
                if (child is not RadialMenuButtonWithSector castChild)
                    continue;

                if (castChild.TargetLayerControlName == proto.Category)
                {
                    castChild.Visible = true;
                    break;
                }
            }
        }

        // Set up menu actions
        foreach (var child in Children)
        {
            AddRCDMenuButtonOnClickActions(child);
        }
    }

    private static string OopsConcat(string a, string b)
    {
        // This exists to prevent Roslyn being clever and compiling something that fails sandbox checks.
        return a + b;
    }

    private void AddRCDMenuButtonOnClickActions(Control control)
    {
        var radialContainer = control as RadialContainer;

        if (radialContainer == null)
            return;

        foreach (var child in radialContainer.Children)
        {
            var castChild = child as RCDMenuButton;

            if (castChild == null)
                continue;

            castChild.OnButtonUp += _ =>
            {
                SendRCDSystemMessageAction?.Invoke(castChild.ProtoId);

                if (_playerManager.LocalSession?.AttachedEntity != null &&
                    _protoManager.TryIndex(castChild.ProtoId, out var proto))
                {
                    var rcdName = _rcd.GetPrototypeName(proto);
                    var msg = Loc.GetString("rcd-component-change-mode", ("mode", rcdName));

                    if (proto.Mode == RcdMode.ConstructTile || proto.Mode == RcdMode.ConstructObject)
                        msg = Loc.GetString("rcd-component-change-build-mode", ("name", rcdName));

                    // Popup message
                    _popup.PopupClient(msg, _owner, _playerManager.LocalSession.AttachedEntity);
                }

                Close();
            };
        }
    }
}

public sealed class RCDMenuButton : RadialMenuButtonWithSector
{
    public ProtoId<RCDPrototype> ProtoId { get; set; }
}
