using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Xenonids.Evolution;

[GenerateTypedNameReferences]
public sealed partial class XenoEvolutionListingControl : Control
{
    public XenoEvolutionListingControl(string name, string description, string price, bool canBuy, Texture? texture = null)
    {
        RobustXamlLoader.Load(this);

        ItemName.Text = name;
        ItemDescription.SetMessage(description);
        ItemTexture.Texture = texture;
        BuyButton.Text = price;
        BuyButton.Disabled = !canBuy;
    }
}
