using Content.Client.Message;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Xenonids.Evolution;

[GenerateTypedNameReferences]
public sealed partial class XenoEvolutionWindow : DefaultWindow
{
    public XenoEvolutionWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPoints(FixedPoint2 points, FixedPoint2 max, bool ready)
    {
        if (max <= 0)
        {
            BalanceInfo.Visible = false;
            HintLabel.Visible = false;
            return;
        }

        BalanceInfo.Visible = true;
        BalanceInfo.SetMarkup(Loc.GetString("rmc-xeno-ui-evolution-points",
            ("points", (int) Math.Floor(points.Double())),
            ("maxPoints", max)));

        HintLabel.Text = Loc.GetString("rmc-xeno-ui-evolution-not-ready");
        HintLabel.Visible = !ready;
    }

    public void ClearListings()
    {
        ListingsContainer.RemoveAllChildren();
    }

    public void AddListing(Control listing)
    {
        ListingsContainer.AddChild(listing);
    }
}
