# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Puro <103608145+PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 Damian Zielińsi <zientasek.pl@gmail.com>
# SPDX-FileCopyrightText: 2026 nikitosych <174215049+nikitosych@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 5h
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: chameleonOutfit
  id: BrigmedicChameleonOutfit
  job: Brigmedic
  hasMindShield: true
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    head: ClothingHeadHatBeretBrigmedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskBreathMedicalSecurity
    gloves: ClothingHandsGlovesNitrile
    shoes: ClothingShoesColorRed
    belt: ClothingBeltMedicalFilled

