using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? ReturnToLobbyPressed;
    public event Action? GhostRolesPressed;
    public event Action? NewLifePressed;
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        ReturnToLobbyButton.OnPressed += _ => ReturnToLobbyPressed?.Invoke();
        NewLifeButton.OnPressed += _ => NewLifePressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody, bool canReturnToLobby = false)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        ReturnToLobbyButton.Visible = canReturnToLobby;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    /// <summary>
    /// Polonium: new life return to the lobby, counting down until it opens.
    /// </summary>
    public void UpdateNewLife(bool visible, TimeSpan remaining)
    {
        NewLifeButton.Visible = visible;
        if (!visible)
            return;

        NewLifeButton.Disabled = remaining > TimeSpan.Zero;
        NewLifeButton.Text = remaining > TimeSpan.Zero
            ? Loc.GetString("ghost-gui-new-life-button-countdown", ("time", $"{(int) remaining.TotalMinutes}:{remaining.Seconds:D2}"))
            : Loc.GetString("ghost-gui-return-to-lobby-button");
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
