using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Polonium.Tutorial.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialHopWindow : DefaultWindow
{
    public event Action? OnConfirm;

    public TutorialHopWindow()
    {
        RobustXamlLoader.Load(this);

        QuestionLabel.SetMarkup(Loc.GetString("intro-training-hop-question"));
        SetCompleted(false);

        ConfirmButton.OnPressed += _ =>
        {
            OnConfirm?.Invoke();
            Close();
        };
        CancelButton.OnPressed += _ => Close();
    }

    public void SetCompleted(bool completed)
    {
        StatusLabel.SetMarkup(Loc.GetString(completed
            ? "intro-training-hop-completed"
            : "intro-training-hop-not-completed"));
    }
}
