using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using System.Numerics;

namespace Content.Client._Polonium.Tutorial.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialBubble : Control
{
    public ClickBehaviour ClickAction { get; set; } = ClickBehaviour.CloseBubble;
    public Tippy TippyVariant { get; set; } = Tippy.ClownRegular;
    public bool FullSize { get; set; }
    public event Action? OnBubbleClosed;
    public BoxContainer ContentContainer => Content;
    public BoxContainer ButtonsContainer => Buttons;
    public RichTextLabel AnyKeyLabel => AnyKeyText;

    [Dependency] private IUserInterfaceManager _ui = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IResourceCache _resCache = default!;

    private readonly TutorialUIController _tutorialUi;

    private const float ComicScale = 0.75f;
    private const int ComicFontSize = 9;

    private bool _comic = true;
    private bool _comicLaidOut;

    public TutorialBubble()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _tutorialUi = _ui.GetUIController<TutorialUIController>();

        ApplyComicStyle();
        MouseFilter = MouseFilterMode.Stop;
        AnyKeyText.Modulate = Color.DarkGray;
    }

    public void ApplyFunctionalStyle()
    {
        _comic = false;

        OuterLayer.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#0E1A1FEE"),
            BorderColor = Color.FromHex("#65B8E2"),
            BorderThickness = new Thickness(2),
            ContentMarginLeftOverride = 18f,
            ContentMarginTopOverride = 10f,
            ContentMarginRightOverride = 18f,
            ContentMarginBottomOverride = 10f,
        };

        MaxWidth = 420;
        ModulateSelfOverride = null;
        TippyVariant = Tippy.None;
        AnyKeyText.Modulate = Color.FromHex("#8FB8CC");
        RecolorLabels(Color.White);
    }

    private void ApplyComicStyle()
    {
        _comic = true;
        var boxTexture = _resCache.GetTexture("/Textures/_Polonium/Interface/Nano/intro_bubble_outer.png");
        OuterLayer.PanelOverride = new StyleBoxTexture
        {
            Texture = boxTexture,
            ContentMarginLeftOverride = 20f,
            ContentMarginTopOverride = 20f,
            ContentMarginRightOverride = 20f,
            ContentMarginBottomOverride = 20f,
            PatchMarginLeft = 12f,
            PatchMarginTop = 12f,
            PatchMarginRight = 12f,
            PatchMarginBottom = 12f,
        };

        ModulateSelfOverride = Color.Transparent;
        RecolorLabels(Color.Black);
    }

    /// <summary>
    /// Default buttons are pale grey and vanish against the light comic bubble, so give the
    /// tutorial its own darker chip with the same blue the rest of the flow uses.
    /// </summary>
    public static Button MakeButton(string text, bool primary = true, bool compact = false)
    {
        var fill = compact ? Color.FromHex("#D0D0D0") : primary ? Color.FromHex("#2C4F63") : Color.FromHex("#4A4A4A");
        var hover = compact ? Color.FromHex("#E4E4E4") : primary ? Color.FromHex("#3A6884") : Color.FromHex("#5C5C5C");

        var button = new Button
        {
            Text = text,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, compact ? 8 : 6, 0, 0),
            MinWidth = compact ? 0 : 190,
        };

        button.AddStyleClass("ButtonSquare");
        if (compact)
        {
            button.AddStyleClass("ButtonSmall");
            button.ModulateSelfOverride = Color.White;
        }

        var style = new StyleBoxFlat
        {
            BackgroundColor = fill,
            BorderColor = compact ? Color.FromHex("#B8B8B8") : Color.FromHex("#65B8E2"),
            BorderThickness = new Thickness(compact ? 1 : 2),
            ContentMarginLeftOverride = compact ? 8f : 14f,
            ContentMarginRightOverride = compact ? 8f : 14f,
            ContentMarginTopOverride = compact ? 2f : 6f,
            ContentMarginBottomOverride = compact ? 2f : 6f,
        };

        button.StyleBoxOverride = style;
        button.Label.Modulate = compact ? Color.FromHex("#333333") : Color.White;

        button.OnMouseEntered += _ => style.BackgroundColor = hover;
        button.OnMouseExited += _ => style.BackgroundColor = fill;

        return button;
    }

    private void RecolorLabels(Color color)
    {
        foreach (var child in BubbleMain.Children)
        {
            if (child is RichTextLabel label)
                label.Modulate = color;
        }
    }

    public TutorialBubble(string text) : this()
    {
        var label = new RichTextLabel
        {
            Text = text,
            Modulate = Color.Black,
        };
        BubbleMain.AddChild(label);
    }

    public TutorialBubble(params string[] texts) : this()
    {
        foreach (var text in texts)
        {
            var label = new RichTextLabel
            {
                Text = text,
                Modulate = Color.Black,
                Margin = new Thickness(0f, 5f),
            };

            BubbleMain.AddChild(label);
        }
    }

    private void CloseBubble()
    {
        OnBubbleClosed?.Invoke();
        Orphan();
    }

    public enum ClickBehaviour
    {
        Ignore,
        CloseBubble,
        CloseOverlay,
        FinishTutorial,
    }

    public enum Tippy
    {
        None,
        ClownRegular,
        ClownPointing,
        WavingHand,
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        AnyKeyText.Visible = ClickAction != ClickBehaviour.Ignore;

        var overlay = _tutorialUi.ActiveOverlay;
        AnyKeyText.Text = overlay is not null && overlay.IsSelfClosingOnClick
            ? _loc.GetString("intro-click-any-to-continue-label")
            : _loc.GetString("intro-click-to-continue-label");

        if (_comic && !FullSize && !_comicLaidOut)
        {
            _comicLaidOut = true;
            ShrinkComicContents();
        }

        if (TippyVariant == Tippy.None)
            return;

        var tippyTexture = TippyVariant switch
        {
            Tippy.ClownRegular => _resCache.GetTexture("/Textures/_Polonium/Interface/Misc/intro_markers/clown.png"),
            Tippy.ClownPointing => _resCache.GetTexture("/Textures/_Polonium/Interface/Misc/intro_markers/clown_tip.png"),
            Tippy.WavingHand => _resCache.GetTexture("/Textures/_Polonium/Interface/Misc/intro_markers/siema.png"),
            _ => throw new ArgumentOutOfRangeException(),
        };

        var tippyScale = _comic && !FullSize ? ComicScale : 1f;
        var tippyIcon = new TextureRect
        {
            Texture = tippyTexture,
            HorizontalAlignment = HAlignment.Right,
            VerticalAlignment = VAlignment.Bottom,
            Margin = new Thickness(0, 0, -80 * tippyScale, -32 * tippyScale),
            SetSize = new Vector2(96 * tippyScale, 96 * tippyScale),
            Stretch = TextureRect.StretchMode.Scale,
            MouseFilter = MouseFilterMode.Ignore,
        };

        OuterLayer.AddChild(tippyIcon);
    }

    private void ShrinkComicContents()
    {
        MaxWidth *= ComicScale;
        if (BubbleMain.MaxWidth < float.PositiveInfinity)
            BubbleMain.MaxWidth *= ComicScale;

        if (OuterLayer.PanelOverride is StyleBoxTexture box)
        {
            box.TextureScale = new Vector2(ComicScale, ComicScale);
            if (box.ContentMarginLeftOverride is { } left)
                box.ContentMarginLeftOverride = left * ComicScale;
            if (box.ContentMarginTopOverride is { } top)
                box.ContentMarginTopOverride = top * ComicScale;
            if (box.ContentMarginRightOverride is { } right)
                box.ContentMarginRightOverride = right * ComicScale;
            if (box.ContentMarginBottomOverride is { } bottom)
                box.ContentMarginBottomOverride = bottom * ComicScale;
        }

        Content.Margin = ScaleThickness(Content.Margin);
        Buttons.Margin = ScaleThickness(Buttons.Margin);
        Content.SeparationOverride = ScaleSep(Content.SeparationOverride);
        Buttons.SeparationOverride = ScaleSep(Buttons.SeparationOverride);

        var font = _resCache.GetFont("/Fonts/Atkinson/AtkinsonHyperlegibleNext-Regular.ttf", ComicFontSize);
        ShrinkControl(this, font);
    }

    private void ShrinkControl(Control control, Font font)
    {
        switch (control)
        {
            case RichTextLabel rich:
                WrapComicFont(rich);
                rich.Margin = ScaleThickness(rich.Margin);
                break;
            case Label label when control.Parent is not Button btn || !btn.HasStyleClass("ButtonSmall"):
                label.FontOverride = font;
                break;
            case Button button:
                if (button.MinWidth > 0)
                    button.MinWidth *= ComicScale;
                button.Margin = ScaleThickness(button.Margin);
                if (button.StyleBoxOverride is StyleBoxFlat flat)
                    ScaleFlat(flat);
                break;
            case TextureRect tex:
                if (tex.Texture is { } texture)
                {
                    var size = tex.SetSize;
                    if (size == default)
                        size = new Vector2(texture.Width, texture.Height);
                    tex.SetSize = size * ComicScale;
                }

                tex.Margin = ScaleThickness(tex.Margin);
                break;
        }

        foreach (var child in control.Children)
            ShrinkControl(child, font);
    }

    private static void WrapComicFont(RichTextLabel label)
    {
        var text = label.Text;
        if (string.IsNullOrEmpty(text) || text.StartsWith("[font size=", StringComparison.Ordinal))
            return;

        label.Text = $"[font size={ComicFontSize}]{text}[/font]";
    }

    private static void ScaleFlat(StyleBoxFlat flat)
    {
        if (flat.ContentMarginLeftOverride is { } left)
            flat.ContentMarginLeftOverride = left * ComicScale;
        if (flat.ContentMarginRightOverride is { } right)
            flat.ContentMarginRightOverride = right * ComicScale;
        if (flat.ContentMarginTopOverride is { } top)
            flat.ContentMarginTopOverride = top * ComicScale;
        if (flat.ContentMarginBottomOverride is { } bottom)
            flat.ContentMarginBottomOverride = bottom * ComicScale;
    }

    private static Thickness ScaleThickness(Thickness thickness)
    {
        return new Thickness(
            thickness.Left * ComicScale,
            thickness.Top * ComicScale,
            thickness.Right * ComicScale,
            thickness.Bottom * ComicScale);
    }

    private static int ScaleSep(int? separation)
    {
        return (int)MathF.Round((separation ?? 10) * ComicScale);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        switch (ClickAction)
        {
            case ClickBehaviour.Ignore:
                break;
            case ClickBehaviour.CloseBubble:
                CloseBubble();
                break;
            case ClickBehaviour.CloseOverlay:
                _tutorialUi.RequestClose(false);
                break;
            case ClickBehaviour.FinishTutorial:
                _tutorialUi.RequestClose(true);
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }

        args.Handle();
    }
}
