// SPDX-FileCopyrightText: 2025 nikitosych <174215049+nikitosych@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Copilot <175728472+Copilot@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Nikita (Nick) <174215049+nikitosych@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Polonium-bot <admin@ss14.pl>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using System.Numerics;

namespace Content.Client._Polonium.Tutorial.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialBubble : Control
{
    public ClickBehaviour ClickAction { get; set; } = ClickBehaviour.CloseBubble;
    public Tippy TippyVariant { get; set; } = Tippy.ClownRegular;
    public event Action? OnBubbleClosed;
    public BoxContainer ContentContainer => Content;
    public BoxContainer ButtonsContainer => Buttons;
    public RichTextLabel AnyKeyLabel => AnyKeyText;

    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;

    private readonly TutorialUIController _tutorialUi;

    public TutorialBubble()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _tutorialUi = _ui.GetUIController<TutorialUIController>();

        var boxTexture = _resCache.GetTexture("/Textures/_Polonium/Interface/Nano/intro_bubble_outer.png");
        OuterLayer.PanelOverride = new StyleBoxTexture
        {
            Texture = boxTexture,
            ContentMarginLeftOverride = 30f,
            ContentMarginTopOverride = 30f,
            ContentMarginRightOverride = 30f,
            ContentMarginBottomOverride = 30f,

            PatchMarginLeft = 12f,
            PatchMarginTop = 12f,
            PatchMarginRight = 12f,
            PatchMarginBottom = 12f,
        };

        MouseFilter = MouseFilterMode.Stop;
        ModulateSelfOverride = Color.Transparent;
        AnyKeyText.Modulate = Color.DarkGray;
    }

    public TutorialBubble(string text) : this()
    {
        var label = new RichTextLabel
        {
            Text = text,
            Modulate = Color.Black,
        };
        BubbleMain.AddChild(label);
    }

    public TutorialBubble(params string[] texts) : this()
    {
        foreach (var text in texts)
        {
            var label = new RichTextLabel
            {
                Text = text,
                Modulate = Color.Black,
                Margin = new Thickness(0f, 5f),
            };

            BubbleMain.AddChild(label);
        }
    }

    private void CloseBubble()
    {
        OnBubbleClosed?.Invoke();
        Orphan();
    }

    public enum ClickBehaviour
    {
        Ignore,
        CloseBubble,
        CloseOverlay,
        FinishTutorial,
    }

    public enum Tippy
    {
        None,
        ClownRegular,
        ClownPointing,
        WavingHand,
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        AnyKeyText.Visible = ClickAction != ClickBehaviour.Ignore;

        var overlay = _tutorialUi.ActiveOverlay;
        AnyKeyText.Text = overlay is not null && overlay.IsSelfClosingOnClick
            ? _loc.GetString("intro-click-any-to-continue-label")
            : _loc.GetString("intro-click-to-continue-label");

        if (TippyVariant == Tippy.None)
            return;

        var tippyTexture = TippyVariant switch
        {
            Tippy.ClownRegular => _resCache.GetTexture("/Textures/_Polonium/Interface/Misc/intro_markers/clown.png"),
            Tippy.ClownPointing => _resCache.GetTexture("/Textures/_Polonium/Interface/Misc/intro_markers/clown_tip.png"),
            Tippy.WavingHand => _resCache.GetTexture("/Textures/_Polonium/Interface/Misc/intro_markers/siema.png"),
            _ => throw new ArgumentOutOfRangeException(),
        };

        var tippyIcon = new TextureRect
        {
            Texture = tippyTexture,
            HorizontalAlignment = HAlignment.Right,
            VerticalAlignment = VAlignment.Bottom,
            Margin = new Thickness(0, 0, -80, -32),
            SetSize = new Vector2(96, 96),
            Stretch = TextureRect.StretchMode.Scale,
            MouseFilter = MouseFilterMode.Ignore,
        };

        OuterLayer.AddChild(tippyIcon);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        switch (ClickAction)
        {
            case ClickBehaviour.Ignore:
                break;
            case ClickBehaviour.CloseBubble:
                CloseBubble();
                break;
            case ClickBehaviour.CloseOverlay:
                _tutorialUi.RequestClose(false);
                break;
            case ClickBehaviour.FinishTutorial:
                _tutorialUi.RequestClose(true);
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }

        args.Handle();
    }
}
