name: Zgłoś Problem
description: Dla problemów, które nie pasują do innych formularzy zgłoszeniowych.
body:
  - type: markdown
    attributes:
      value: |
        Dziękujemy za poświęcenie czasu na zgłoszenie problemu. Ten formularz jest dla problemów, które nie pasują do innych formularzy.
  - type: textarea
    attributes:
      label: Opis
      description: |
        Jasny i zwięzły opis problemu.
        Jeżeli problem jest wizualny, dołącz zrzut ekranu.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Lista kroków do odtworzenia
      description: Lista kroków wymaganych, aby odtworzyć problem.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Dodatkowy kontekst
      description: W tym polu można dopisać dodatkowy kontekst związany z problemem.
    validations:
      required: false

