using Content.Client.RichText;
using Content.Client.UserInterface.Screens;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Polonium.Tutorial.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialControlHint : Control
{
    private const float MinChatGap = 10f;
    private const float FallbackInset = 12f;
    private const float FallbackTop = 44f;

    private string _details = string.Empty;
    private bool _expanded;

    public TutorialControlHint()
    {
        RobustXamlLoader.Load(this);
        StyleMoreButton();
        MoreButton.OnPressed += _ =>
        {
            _expanded = !_expanded;
            UpdateDetails();
        };
    }

    /// <summary>
    /// Top line is what the step wants, bottom line is which keys do it. Either half can be empty.
    /// Details are the long explanation, folded behind a button so the bar stays short.
    /// </summary>
    public void SetHint(string objective, string keys, string details = "")
    {
        var hasObjective = !string.IsNullOrWhiteSpace(objective);
        var hasKeys = !string.IsNullOrWhiteSpace(keys);

        // a new step starts folded, a keybind refresh of the same step keeps what the player chose
        if (details != _details)
        {
            _details = details;
            _expanded = false;

            if (!string.IsNullOrWhiteSpace(details))
                DetailsLabel.SetMessage(FormattedMessage.FromMarkupPermissive(details), UserFormattableTags.BaseAllowedTags);
        }

        UpdateDetails();

        if (!hasObjective && !hasKeys)
        {
            Visible = false;
            return;
        }

        if (hasObjective)
            ObjectiveLabel.SetMessage(FormattedMessage.FromMarkupPermissive(objective), UserFormattableTags.BaseAllowedTags);

        if (hasKeys)
            HintLabel.SetMessage(FormattedMessage.FromMarkupPermissive(keys), UserFormattableTags.BaseAllowedTags);

        ObjectiveLabel.Visible = hasObjective;
        HintLabel.Visible = hasKeys;
        HintSeparator.Visible = hasObjective && hasKeys;
        Visible = true;
    }

    private void StyleMoreButton()
    {
        var fill = Color.FromHex("#2C4F63");
        var hover = Color.FromHex("#3A6884");
        var style = new StyleBoxFlat
        {
            BackgroundColor = fill,
            BorderColor = Color.FromHex("#65B8E2"),
            BorderThickness = new Thickness(2),
            ContentMarginLeftOverride = 14f,
            ContentMarginRightOverride = 14f,
            ContentMarginTopOverride = 6f,
            ContentMarginBottomOverride = 6f,
        };

        MoreButton.StyleBoxOverride = style;
        MoreButton.Label.Modulate = Color.White;
        MoreButton.OnMouseEntered += _ => style.BackgroundColor = hover;
        MoreButton.OnMouseExited += _ => style.BackgroundColor = fill;
    }

    private void UpdateDetails()
    {
        var hasDetails = !string.IsNullOrWhiteSpace(_details);
        MoreButton.Visible = hasDetails;
        DetailsLabel.Visible = hasDetails && _expanded;
        MoreButton.Text = Loc.GetString(_expanded ? "tutorial-hint-less" : "tutorial-hint-more");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!Visible)
            return;

        var right = FallbackInset;
        var top = FallbackTop;

        if (UserInterfaceManager.ActiveScreen is InGameScreen screen)
        {
            var chat = screen.ChatBox;
            if (chat is { Visible: true } && chat.Size.X > 0)
            {
                top = Math.Max(0f, chat.GlobalPosition.Y - GlobalPosition.Y);

                // same inset as the chat's top gap so it doesnt sit flush on the box
                var gap = Math.Max(MinChatGap, top);
                var chatLeft = chat.GlobalPosition.X - GlobalPosition.X;
                right = Math.Max(gap, Width - chatLeft + gap);
            }
        }

        var margin = new Thickness(0, top, right, 0);
        if (!HintPanel.Margin.Equals(margin))
            HintPanel.Margin = margin;
    }
}
