using Content.Client.RichText;
using Content.Client.UserInterface.Screens;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Polonium.Tutorial.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialControlHint : Control
{
    private const float MinChatGap = 10f;
    private const float FallbackInset = 12f;
    private const float FallbackTop = 44f;

    public TutorialControlHint()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Top line is what the step wants, bottom line is which keys do it. Either half can be empty.
    /// </summary>
    public void SetHint(string objective, string keys)
    {
        var hasObjective = !string.IsNullOrWhiteSpace(objective);
        var hasKeys = !string.IsNullOrWhiteSpace(keys);

        if (!hasObjective && !hasKeys)
        {
            Visible = false;
            return;
        }

        if (hasObjective)
            ObjectiveLabel.SetMessage(FormattedMessage.FromMarkupPermissive(objective), UserFormattableTags.BaseAllowedTags);

        if (hasKeys)
            HintLabel.SetMessage(FormattedMessage.FromMarkupPermissive(keys), UserFormattableTags.BaseAllowedTags);

        ObjectiveLabel.Visible = hasObjective;
        HintLabel.Visible = hasKeys;
        HintSeparator.Visible = hasObjective && hasKeys;
        Visible = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!Visible)
            return;

        var right = FallbackInset;
        var top = FallbackTop;

        if (UserInterfaceManager.ActiveScreen is InGameScreen screen)
        {
            var chat = screen.ChatBox;
            if (chat is { Visible: true } && chat.Size.X > 0)
            {
                top = Math.Max(0f, chat.GlobalPosition.Y - GlobalPosition.Y);

                // same inset as the chat's top gap so it doesnt sit flush on the box
                var gap = Math.Max(MinChatGap, top);
                var chatLeft = chat.GlobalPosition.X - GlobalPosition.X;
                right = Math.Max(gap, Width - chatLeft + gap);
            }
        }

        var margin = new Thickness(0, top, right, 0);
        if (!HintPanel.Margin.Equals(margin))
            HintPanel.Margin = margin;
    }
}
