using System.Text;
using Content.Client.ContextMenu.UI;
using Content.Client.Gameplay;
using Content.Client.Viewport;
using Content.Shared._Polonium.Tutorial.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map.Components;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Polonium.Tutorial.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialAnchorLabelerWindow : DefaultWindow
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IInputManager _input = default!;
    [Dependency] private IStateManager _state = default!;
    [Dependency] private IUserInterfaceManager _ui = default!;

    public event Action<string>? OnAnchorChanged;

    private bool _focused;
    private string _anchor = string.Empty;
    private string _initialAnchor = string.Empty;
    private string _lastHover = string.Empty;

    public TutorialAnchorLabelerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LabelLineEdit.OnTextChanged += e =>
        {
            _anchor = e.Text;
            OnAnchorChanged?.Invoke(_anchor);
            UpdateButtons();
        };

        LabelLineEdit.OnFocusEnter += _ => _focused = true;
        LabelLineEdit.OnFocusExit += _ =>
        {
            _focused = false;
            LabelLineEdit.Text = _anchor;
        };
        ResetLabelButton.OnPressed += _ => LabelLineEdit.SetText(_initialAnchor, true);
        ClearLabelButton.OnPressed += _ => LabelLineEdit.SetText("", true);
    }

    protected override void Opened()
    {
        base.Opened();
        LabelLineEdit.GrabKeyboardFocus();
    }

    public void SetCurrentAnchor(string anchor)
    {
        if (anchor == _anchor)
            return;

        _anchor = anchor;
        if (!_focused)
        {
            LabelLineEdit.Text = anchor;
            UpdateButtons();
        }
    }

    public void SetInitialAnchorState()
    {
        LabelLineEdit.Text = _anchor;
        LabelLineEdit.CursorPosition = _anchor.Length;
        LabelLineEdit.SelectionStart = 0;
        _initialAnchor = _anchor;
        UpdateButtons();
    }

    public void UpdateButtons()
    {
        ResetLabelButton.Disabled = LabelLineEdit.Text == _initialAnchor;
        ClearLabelButton.Disabled = LabelLineEdit.Text == "";
    }

    public void SetMaxAnchorLength(int maxLength)
    {
        LabelLineEdit.IsValid = s => s.Length <= maxLength;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateHover();
    }

    private void UpdateHover()
    {
        var text = BuildHoverText();
        if (text == _lastHover)
            return;

        _lastHover = text;
        var msg = new FormattedMessage();
        msg.AddText(text);
        HoverLabel.SetMessage(msg);
    }

    private string BuildHoverText()
    {
        if (_state.CurrentState is not GameplayStateBase screen)
            return Loc.GetString("tutorial-anchor-labeler-hover-none");

        if (_ui.CurrentlyHovered is EntityMenuElement { Entity: { } menuEnt })
            return FormatEntity(menuEnt);

        // over the window still - keep last ent so you can actually read it
        if (_ui.CurrentlyHovered is not IViewportControl vp || !_input.MouseScreenPosition.IsValid)
            return string.IsNullOrEmpty(_lastHover)
                ? Loc.GetString("tutorial-anchor-labeler-hover-none")
                : _lastHover;

        var mousePos = vp.PixelToMap(_input.MouseScreenPosition.Position);
        var ents = vp is ScalingViewport svp
            ? screen.GetClickableEntities(mousePos, svp.Eye)
            : screen.GetClickableEntities(mousePos);

        var sb = new StringBuilder();
        var n = 0;
        foreach (var uid in ents)
        {
            if (n >= 10)
                break;

            if (_ent.HasComponent<MapComponent>(uid) || _ent.HasComponent<MapGridComponent>(uid))
                continue;

            if (n > 0)
                sb.Append('\n');

            sb.Append(FormatEntity(uid));
            n++;
        }

        return n == 0
            ? Loc.GetString("tutorial-anchor-labeler-hover-none")
            : sb.ToString();
    }

    private string FormatEntity(EntityUid uid)
    {
        if (!_ent.EntityExists(uid))
            return Loc.GetString("tutorial-anchor-labeler-hover-none");

        var name = _ent.GetComponent<MetaDataComponent>(uid).EntityName;
        var net = _ent.GetNetEntity(uid);
        var id = Loc.GetString("tutorial-anchor-labeler-hover-no-anchor");
        if (_ent.TryGetComponent(uid, out TutorialAnchorComponent? anchor)
            && !string.IsNullOrEmpty(anchor.AnchorId))
            id = anchor.AnchorId;

        return Loc.GetString("tutorial-anchor-labeler-hover-line",
            ("entity", name),
            ("uid", net),
            ("anchor", id));
    }
}
