using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Polonium.CallablePhone.UI;

[GenerateTypedNameReferences]
public sealed partial class CallablePhoneAdminCallPickupWindow : FancyWindow
{
    public event Action? Accepted;
    public event Action? Declined;

    public CallablePhoneAdminCallPickupWindow(string message)
    {
        RobustXamlLoader.Load(this);

        MessageLabel.Text = message;

        AcceptButton.OnPressed += _ =>
        {
            Accepted?.Invoke();
            Close();
        };

        DeclineButton.OnPressed += _ =>
        {
            Declined?.Invoke();
            Close();
        };

        OnClose += () =>
        {
            Accepted = null;
            Declined = null;
        };
    }
}

