- type: gameMapPool
  id: DefaultMapPool
  maps:
  # _Polonium
  - DeathStar
  - Terra
  - Cluster
  - Saltern
  - Cork
  - Atlas
  - Reach
  # - Amber
  # - Eden
  # - roid_outpost
  # other
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Exo
  - Snowball
  - Serpentcrest
