// SPDX-FileCopyrightText: 2025 Polonium Station Contributors
//
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class EntitySearchWindow : DefaultWindow
{
    private readonly IClientConsoleHost _console;
    private readonly ILocalizationManager _loc;

    public event Action? SearchRequested;

    public EntitySearchWindow(IClientConsoleHost console, ILocalizationManager loc)
    {
        _console = console;
        _loc = loc;

        RobustXamlLoader.Load(this);

        SearchButton.OnPressed += _ => SearchRequested?.Invoke();
        SearchLineEdit.OnTextEntered += _ => SearchRequested?.Invoke();
    }

    public string SearchText => SearchLineEdit.Text;

    public void UpdateResults((string name, NetEntity entity)[] entities)
    {
        AdminEntityResultsList.Populate(ItemList, StatusLabel, entities, _console, _loc);
    }
}
