- type: ghostRoleRaffleSettings
  id: default
  settings:
    initialDuration: 45
    joinExtendsDurationBy: 2
    maxDuration: 45

# for roles that don't matter too much or are available plentifully (e.g. space carp)
- type: ghostRoleRaffleSettings
  id: short
  settings:
    initialDuration: 15
    joinExtendsDurationBy: 0
    maxDuration: 15

# xenomorph larva ghost role
- type: ghostRoleRaffleSettings
  id: xeno-larva
  settings:
    initialDuration: 30
    joinExtendsDurationBy: 0
    maxDuration: 30
