using Content.Shared._Polonium.VendingMachines;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Polonium.VendingMachines.UI;

public enum VendingMachineKeypadFeedback : byte
{
    None,    // machine busy/off: the keypad just doesn't respond
    Success,
    Empty,   // slot sold out
    Invalid, // incomplete or unmapped code
    Denied,  // access denied
}

[GenerateTypedNameReferences]
public sealed partial class VendingMachineKeypadMenu : FancyWindow
{
    [Dependency] private IRobustRandom _random = null!;
    [Dependency] private IEntityManager _entManager = null!;
    private readonly SharedAudioSystem _audio;

    public event Func<int, VendingMachineKeypadFeedback>? OnCodeEntered;
    public event Action<VendingMachineKeypadSound, float>? OnAudioPlayed;

    private readonly List<VendingMachineGridSlot> _slots = new();

    public EntityUid VendingMachineOwner;
    public EntityUid? User;

    private int _rowCount;
    private char? _bufferLetter;
    private int? _bufferNumber;

    // timers & state
    private float _blinkTimer;
    private float _inactivityTimer;
    private float _powerSagTimer;
    private float _chuteRattleDelay;
    private float _chuteRattleTimer;
    private bool _cursorVisible = true;
    private bool _showingFeedback;

    // flavor text
    private readonly string[] _successPhrases =
    [
        "vending-machine-keypad-feedback-success-1",
        "vending-machine-keypad-feedback-success-2",
        "vending-machine-keypad-feedback-success-3",
        "vending-machine-keypad-feedback-success-4",
    ];

    // nuke C scale
    private readonly int[] _bluesScale = [0, 2, 3, 4, 5, 6, 7, 9, 10];

    // colors
    private readonly Color _redOffColor = Color.FromHex("#440000");
    private readonly Color _redOnColor = Color.FromHex("#ff3333");
    private readonly Color _greenOffColor = Color.FromHex("#004400");
    private readonly Color _greenOnColor = Color.FromHex("#33ff33");

    public VendingMachineKeypadMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = _entManager.System<SharedAudioSystem>();

        BuildNumpad();
        ResetLedIndicators();
        UpdateBufferLabel();
    }

    private void BuildNumpad()
    {
        NumpadGrid.RemoveAllChildren();

        for (var i = 1; i <= 9; i++)
        {
            var number = i;
            var shift = _bluesScale[number - 1]; // map 1-9 to the scale
            var pitch = MathF.Pow(2f, shift / 12f);

            var key = new VendingMachineKeypadKey(number.ToString());
            key.OnKeyPressed += () => OnNumberPressed(number, pitch);
            NumpadGrid.AddChild(key);
        }

        var clearKey = new VendingMachineKeypadKey(Loc.GetString("vending-machine-keypad-clear"));
        clearKey.SetTint(Color.FromHex("#ffb3b3"), Color.FromHex("#ffcccc"), Color.FromHex("#800000"));
        clearKey.OnKeyPressed += () =>
        {
            if (_showingFeedback)
                return;

            PlayKeypadSound(VendingMachineKeypadSound.Beep, 0.7f);
            ClearBuffer();
        };
        NumpadGrid.AddChild(clearKey);

        var zeroKey = new VendingMachineKeypadKey("0");
        zeroKey.OnKeyPressed += () => OnNumberPressed(0, MathF.Pow(2f, 12f / 12f));
        NumpadGrid.AddChild(zeroKey);

        var enterKey = new VendingMachineKeypadKey(Loc.GetString("vending-machine-keypad-enter"));
        enterKey.SetTint(Color.FromHex("#b3ffb3"), Color.FromHex("#ccffcc"), Color.FromHex("#004d00"));
        enterKey.OnKeyPressed += SubmitBuffer;
        NumpadGrid.AddChild(enterKey);
    }

    private void BuildLetterGrid()
    {
        LetterGrid.RemoveAllChildren();

        for (var row = 0; row < _rowCount; row++)
        {
            var letter = (char)('A' + row);
            var capturedLetter = letter;

            var shift = _bluesScale[row % _bluesScale.Length] - 12;
            var pitch = MathF.Pow(2f, shift / 12f);

            var key = new VendingMachineKeypadKey(letter.ToString());
            key.OnKeyPressed += () => OnLetterPressed(capturedLetter, pitch);
            LetterGrid.AddChild(key);
        }
    }

    public void Populate(List<VendingMachineInventoryEntry> inventory)
    {
        ItemGrid.RemoveAllChildren();
        _slots.Clear();

        // map 10 slots per letter
        _rowCount = inventory.Count == 0 ? 0 : (inventory.Count - 1) / 10 + 1;

        for (var i = 0; i < inventory.Count; i++)
        {
            var entry = inventory[i];
            var code = GetCode(i);

            var slot = new VendingMachineGridSlot();
            slot.SetItem(entry.ID, code, entry.Amount, entry.Amount == 0);

            ItemGrid.AddChild(slot);
            _slots.Add(slot);
        }

        BuildLetterGrid();

        // keep a half-typed code across inventory refreshes, dropping it only
        // if its row fell off the rebuilt grid; during feedback the buffer is
        // already empty and the label holds feedback text, so just re-apply
        // highlights to the new slots.
        if (_bufferLetter is { } bufferLetter && bufferLetter - 'A' >= _rowCount)
            _bufferLetter = null;

        if (_showingFeedback)
            UpdateHighlights();
        else
            UpdateBufferLabel();
    }

    public void UpdateAmounts(List<VendingMachineInventoryEntry> inventory)
    {
        if (inventory.Count != _slots.Count)
        {
            Populate(inventory);
            return;
        }

        for (var i = 0; i < inventory.Count; i++)
        {
            _slots[i].SetAmount(inventory[i].Amount, inventory[i].Amount == 0);
        }
    }

    public void PlayVendAnimation(int slotIndex)
    {
        if (slotIndex < 0 || slotIndex >= _slots.Count)
            return;

        _slots[slotIndex].PlayVendAnimation();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // power sag when vending
        if (_powerSagTimer > 0)
        {
            _powerSagTimer -= args.DeltaSeconds;
            var sagAmount = Math.Clamp(_powerSagTimer / 0.15f, 0f, 1f);
            var brightness = 1f - (sagAmount * 0.6f); // dim to 40% brightness momentarily
            var dimColor = new Color(brightness, brightness, brightness);

            ScreenBackground.Modulate = dimColor;
        }
        else
        {
            ScreenBackground.Modulate = Color.White;
        }

        if (_chuteRattleDelay > 0)
        {
            _chuteRattleDelay -= args.DeltaSeconds;
        }
        else if (_chuteRattleTimer > 0)
        {
            _chuteRattleTimer -= args.DeltaSeconds;

            if (_chuteRattleTimer > 0)
            {
                var offset = _random.NextFloat(-2f, 2f);
                DispenseChute.Margin = new Thickness(0, offset, 0, -offset);
            }
            else
            {
                DispenseChute.Margin = new Thickness(0);
            }
        }

        if (_showingFeedback)
            return;

        // blinking cursor
        _blinkTimer += args.DeltaSeconds;
        if (_blinkTimer >= 0.5f)
        {
            _blinkTimer = 0f;
            _cursorVisible = !_cursorVisible;
            UpdateBufferLabel();
        }

        // inactivity timeout
        if (_bufferLetter != null || _bufferNumber != null)
        {
            _inactivityTimer += args.DeltaSeconds;
            if (_inactivityTimer >= 15f)
            {
                PlayKeypadSound(VendingMachineKeypadSound.Timeout, 0.6f);

                _bufferLetter = null;
                _bufferNumber = null;
                _inactivityTimer = 0f;
                UpdateBufferLabel();
            }
        }
    }

    private void OnLetterPressed(char letter, float pitch)
    {
        if (_showingFeedback)
            return;

        PlayKeypadSound(VendingMachineKeypadSound.Beep, pitch);

        _bufferLetter = letter;
        _cursorVisible = true;
        _blinkTimer = 0f;
        _inactivityTimer = 0f;
        UpdateBufferLabel();
    }

    private void OnNumberPressed(int number, float pitch)
    {
        if (_showingFeedback)
            return;

        PlayKeypadSound(VendingMachineKeypadSound.Beep, pitch);

        _bufferNumber = number;
        _cursorVisible = true;
        _blinkTimer = 0f;
        _inactivityTimer = 0f;
        UpdateBufferLabel();
    }

    private void ClearBuffer()
    {
        if (_showingFeedback)
            return;

        _bufferLetter = null;
        _bufferNumber = null;
        _cursorVisible = true;
        _blinkTimer = 0f;
        _inactivityTimer = 0f;
        UpdateBufferLabel();
    }

    private void SubmitBuffer()
    {
        if (_showingFeedback)
            return;

        if (_bufferLetter is not { } letter || _bufferNumber is not { } number)
        {
            ShowFeedback(VendingMachineKeypadFeedback.Invalid);
            return;
        }

        var row = letter - 'A';
        var index = row * 10 + number;

        if (index >= 0 && index < _slots.Count)
        {
            var slot = _slots[index];
            if (slot.SoldOut)
            {
                ShowFeedback(VendingMachineKeypadFeedback.Empty);
                return;
            }

            var feedback = OnCodeEntered?.Invoke(index) ?? VendingMachineKeypadFeedback.Success;
            if (feedback == VendingMachineKeypadFeedback.None)
                return;

            if (feedback != VendingMachineKeypadFeedback.Success)
            {
                ShowFeedback(feedback);
                return;
            }

            ShowFeedback(VendingMachineKeypadFeedback.Success);

            _chuteRattleDelay = 0.55f;
            _chuteRattleTimer = 0.35f;
        }
        else
        {
            ShowFeedback(VendingMachineKeypadFeedback.Invalid);
        }
    }

    private void ShowFeedback(VendingMachineKeypadFeedback feedback)
    {
        _bufferLetter = null;
        _bufferNumber = null;
        _showingFeedback = true;

        if (feedback == VendingMachineKeypadFeedback.Success)
        {
            BufferLabel.FontColorOverride = Color.Green;
            BufferLabel.Text = Loc.GetString(_random.Pick(_successPhrases));
            GreenLed.Modulate = _greenOnColor;
            PlayKeypadSound(VendingMachineKeypadSound.Success);

            _powerSagTimer = 0.15f;
        }
        else
        {
            BufferLabel.FontColorOverride = Color.Red;
            BufferLabel.Text = Loc.GetString(feedback switch
            {
                VendingMachineKeypadFeedback.Empty => "vending-machine-keypad-feedback-empty",
                VendingMachineKeypadFeedback.Denied => "vending-machine-keypad-feedback-denied",
                _ => "vending-machine-keypad-feedback-invalid",
            });
            RedLed.Modulate = _redOnColor;
            PlayKeypadSound(VendingMachineKeypadSound.Error);
        }

        UpdateHighlights();

        Timer.Spawn(TimeSpan.FromSeconds(0.75),
            () =>
        {
            if (Disposed)
                return;

            _showingFeedback = false;
            ResetLedIndicators();
            BufferLabel.FontColorOverride = Color.FromHex("#33ff33");
            UpdateBufferLabel();
        });
    }

    private void PlayKeypadSound(VendingMachineKeypadSound sound, float pitch = 1f)
    {
        var (path, volume) = VendingMachineKeypadSounds.Get(sound);
        _audio.PlayPredicted(new SoundPathSpecifier(path), VendingMachineOwner, User, new AudioParams().WithVolume(volume).WithPitchScale(pitch));
        OnAudioPlayed?.Invoke(sound, pitch);
    }

    private void ResetLedIndicators()
    {
        RedLed.Modulate = _redOffColor;
        GreenLed.Modulate = _greenOffColor;
    }

    private void UpdateBufferLabel()
    {
        // if there's no letter, blink the first slot.
        // if there's a letter but no number, blink the second slot.
        var letterText = _bufferLetter?.ToString() ?? (_cursorVisible && _bufferNumber == null ? "_" : "-");
        var numberText = _bufferNumber?.ToString() ?? (_cursorVisible && _bufferLetter != null && _bufferNumber == null ? "_" : "-");

        BufferLabel.Text = $"[ {letterText} {numberText} ]";

        UpdateHighlights();
    }

    private void UpdateHighlights()
    {
        for (var i = 0; i < _slots.Count; i++)
        {
            var row = i / 10;
            var col = i % 10;
            var letter = (char)('A' + row);

            var isRowMatch = _bufferLetter == letter;
            var isExactMatch = isRowMatch && _bufferNumber == col;

            _slots[i].SetHighlight(isRowMatch, isExactMatch);
        }
    }

    private static string GetCode(int index)
    {
        var row = index / 10;
        var col = index % 10;
        var letter = (char)('A' + row);
        return $"{letter}{col}";
    }
}
