// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Polonium.Prayer.UI;

[GenerateTypedNameReferences]
public sealed partial class CentCommCallPickupWindow : FancyWindow
{
    public event Action? Accepted;
    public event Action? Declined;

    public CentCommCallPickupWindow(string message)
    {
        RobustXamlLoader.Load(this);

        MessageLabel.Text = message;

        AcceptButton.OnPressed += _ =>
        {
            Accepted?.Invoke();
            Close();
        };

        DeclineButton.OnPressed += _ =>
        {
            Declined?.Invoke();
            Close();
        };

        OnClose += () =>
        {
            Accepted = null;
            Declined = null;
        };
    }
}
