using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.FirelockBolt;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.FirelockBolt;

[GenerateTypedNameReferences]
public sealed partial class FirelockOverrideWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = null!;
    private readonly SharedAudioSystem _audio;

    public event Action<bool>? SetOverride;

    // Dimensions
    private const float UiScale = 2f;

    private const float ContainerWidth = 64f * UiScale;
    private const float TrackWidth = 32f * UiScale;
    private const float HandleWidth = 64f * UiScale;

    private const float TrackHeight = 160f * UiScale;
    private const float HandleHeight = 32f * UiScale;
    private const float TravelDistance = TrackHeight - HandleHeight;
    private const float CommitThreshold = 0.7f;

    // ratchet clicky steps
    private const int RatchetSteps = 6;
    private int _lastRatchetStep = -1;

    private bool _dragging;
    private bool _currentOverride;
    private float _handlePos;

    public FirelockOverrideWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = _entManager.System<SharedAudioSystem>();

        LeverHandle.MouseFilter = MouseFilterMode.Stop;
        LeverTrack.MouseFilter = MouseFilterMode.Stop;

        LeverHandle.OnKeyBindDown += OnHandleGrab;
        LeverTrack.OnKeyBindDown += OnHandleGrab;

        LeverHandle.OnKeyBindUp += OnHandleRelease;
        LeverTrack.OnKeyBindUp += OnHandleRelease;
    }

    public void UpdateState(FirelockOverrideBuiState state)
    {
        _currentOverride = state.Override;

        if (!_dragging)
        {
            _handlePos = state.Override ? 1f : 0f;
            _lastRatchetStep = (int)Math.Round(_handlePos * RatchetSteps);
            UpdateVisual();
        }

        var statusText = state.Override
            ? Loc.GetString("firelock-bolt-control-window-status-override")
            : state.Bolted
                ? Loc.GetString("firelock-bolt-control-window-status-locked")
                : Loc.GetString("firelock-bolt-control-window-status-unlocked");
        var statusColor = state.Override ? "#e5a93b" : (state.Bolted ? "#d32f2f" : "#388e3c");
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow($"[color={statusColor}][bold]{statusText.ToUpper()}[/bold][/color]");
        StatusLabel.SetMessage(msg);
    }

    private void OnHandleGrab(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = true;
        args.Handle();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_dragging)
            return;

        var mouseGlobalY = UserInterfaceManager.MousePositionScaled.Position.Y;
        var trackGlobalY = LeverTrack.GlobalPosition.Y;

        var relativeY = mouseGlobalY - trackGlobalY - (HandleHeight / 2f);
        var relative = Math.Clamp(relativeY / TravelDistance, 0f, 1f);

        // friction curve
        var centered = (relative - 0.5f) * 2f;
        var curved = centered * centered * centered;
        _handlePos = (curved + 1f) / 2f;

        // snapping
        if (_handlePos > 0.90f)
            _handlePos = 1f;
        else if (_handlePos < 0.10f)
            _handlePos = 0f;

        UpdateVisual();
        ProcessRatchetAudio();
    }

    private void ProcessRatchetAudio()
    {
        var currentStep = (int)Math.Round(_handlePos * RatchetSteps);

        if (currentStep != _lastRatchetStep)
        {
            if (_lastRatchetStep != -1)
            {
                var isEdge = currentStep == 0 || currentStep == RatchetSteps;
                var volume = isEdge ? 0f : -6f;

                var progress = currentStep / (float)RatchetSteps;

                // change pitch based on lever, 1.2f at step 0, down to 0.8f at max step
                var pitch = 1.2f - (progress * 0.4f);

                var audioParams = new AudioParams()
                    .WithVolume(volume)
                    .WithPitchScale(pitch);

                _audio.PlayGlobal(new SoundPathSpecifier("/Audio/_Funkystation/Effects/ratchet_click.ogg"), Filter.Local(), false, audioParams);
            }

            _lastRatchetStep = currentStep;
        }
    }

    private void OnHandleRelease(GUIBoundKeyEventArgs args)
    {
        if (!_dragging || args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = false;
        args.Handle();

        bool? commit = null;
        if (_handlePos >= CommitThreshold)
            commit = true;
        else if (_handlePos <= 1f - CommitThreshold)
            commit = false;

        if (commit is { } value)
        {
            if (value != _currentOverride)
                SetOverride?.Invoke(value);

            _handlePos = value ? 1f : 0f;
        }
        else
        {
            _handlePos = _currentOverride ? 1f : 0f;
        }

        _lastRatchetStep = (int)Math.Round(_handlePos * RatchetSteps);
        UpdateVisual();
    }

    private void UpdateVisual()
    {
        var y = _handlePos * TravelDistance;

        var trackX = (ContainerWidth - TrackWidth) / 2f;
        LayoutContainer.SetPosition(TrackImage, new Vector2(trackX, 0));

        var handleX = (ContainerWidth - HandleWidth) / 2f;
        LayoutContainer.SetPosition(LeverHandle, new Vector2(handleX, y));
    }
}
