// SPDX-FileCopyrightText: 2023 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2026 Whatstone <166147148+whatston3@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 maciejwalendziuk <15122746+maciejwalendziuk@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 nikitosych <174215049+nikitosych@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 taydeo <tay@funkystation.org>
// SPDX-FileCopyrightText: 2026 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampCollection : Container
{
    private List<StampWidget> _stamps = new();

    /// Seed for random number generator to place stamps deterministically
    public int PlacementSeed;

    /// Height (virtual px) of the fixed blank band under the text that auto-placed
    /// stamps scatter within. Mirrors the StampReserve spacer in PaperWindow.xaml.
    private const float BandHeightVirtual = 180f;

    /// The written-text control. Auto-placed stamps scatter in the area BELOW
    /// its bottom edge so they never cover the text. Null = scatter over the
    /// whole page (e.g. a blank sheet).
    public Control? TextRegion;

    public StampCollection()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Remove any stamps from the page
    /// </summary>
    public void RemoveStamps()
    {
        _stamps.Clear();
        InvalidateArrange();
    }

    /// <summary>
    /// Adds a stamp to the display; will perform
    /// automatic layout.
    /// </summary>
    public void AddStamp(StampWidget s)
    {
        _stamps.Add(s);
        AddChild(s);
    }

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        var random = new RobustRandom();
        random.SetSeed(PlacementSeed);

        var sizePx = finalSize * UIScale;
        var origin = PixelSizeBox.TopLeft;
        var controlBox = new UIBox2(origin, origin + sizePx);

        // Local Y just below the written text; auto stamps scatter between here
        // and the page bottom so they never cover the text. 0 = top (blank sheet).
        var textBottom = 0f;
        if (TextRegion != null)
            textBottom = TextRegion.GlobalPixelPosition.Y + TextRegion.PixelSize.Y - GlobalPixelPosition.Y;
        textBottom = Math.Clamp(textBottom, 0f, sizePx.Y);

        // Auto-placed stamps scatter randomly in the band under the text.
        // Explicitly-placed marks (signatures, manually-placed stamps) use their
        // stored normalized position. Kept separate so plain stamps render as
        // they did before signatures existed.
        for (var i = 0; i < _stamps.Count; i++)
        {
            var stamp = _stamps[i];
            var childHeLocal = stamp.DesiredPixelSize * 0.5f;

            float stampOrientation;
            if (stamp.HasExplicitTransform)
                stampOrientation = stamp.Orientation;
            else
            {
                stampOrientation = MathHelper.DegreesToRadians((random.NextFloat() - 0.5f) * 10.0f);
                stamp.Orientation = stampOrientation;
            }

            var c = childHeLocal * MathF.Abs(MathF.Cos(stampOrientation));
            var s = childHeLocal * MathF.Abs(MathF.Sin(stampOrientation));
            var childHePage = new Vector2(c.X + s.Y, s.X + c.Y);

            Vector2 childCenter;
            if (stamp.HasExplicitTransform)
            {
                childCenter = origin + sizePx * stamp.NormalizedPosition;
            }
            else
            {
                // Random center bounded to the fixed band under the text so the
                // whole (tilted) stamp stays inside it and clears the text.
                var bandBottom = MathF.Min(controlBox.Bottom, origin.Y + textBottom + BandHeightVirtual * UIScale);
                var minX = origin.X + childHePage.X;
                var maxX = controlBox.Right - childHePage.X;
                var minY = origin.Y + textBottom + childHePage.Y;
                var maxY = bandBottom - childHePage.Y;
                var cx = maxX > minX ? minX + random.NextFloat() * (maxX - minX) : (minX + maxX) * 0.5f;
                var cy = maxY > minY ? minY + random.NextFloat() * (maxY - minY) : (minY + maxY) * 0.5f;
                childCenter = new Vector2(cx, cy);
            }

            var clampedCenter = Clamp(Shrink(controlBox, childHePage), childCenter);
            var finalPosition = stamp.HasExplicitTransform
                ? clampedCenter - childHeLocal
                : clampedCenter - childHePage;
            var finalPositionAsInt = new Vector2i((int)finalPosition.X, (int)finalPosition.Y);
            stamp.ArrangePixel(new UIBox2i(finalPositionAsInt, finalPositionAsInt + stamp.DesiredPixelSize));
        }

        return finalSize;
    }

    /// <summary>
    /// Shrink a UIBox2 by a half extents, moving both the top-left and
    /// bottom-right closer together.
    /// </summary>
    private UIBox2 Shrink(UIBox2 box, Vector2 shrinkHe)
    {
        return new UIBox2(box.TopLeft + shrinkHe, box.BottomRight - shrinkHe);
    }

    /// <summary>
    /// Returns the input vector clamped to be within the UIBox
    /// </summary>
    private Vector2 Clamp(UIBox2 box, Vector2 point)
    {
        return Vector2.Min(box.BottomRight, Vector2.Max(box.TopLeft, point));
    }
}

