// SPDX-FileCopyrightText: 2024 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2025 Tayrtahn <tayrtahn@gmail.com>
// SPDX-FileCopyrightText: 2025 V <97265903+formlessnameless@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 maciejwalendziuk <15122746+maciejwalendziuk@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 taydeo <tay@funkystation.org>
// SPDX-FileCopyrightText: 2026 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampLabel : Label
{
    private static readonly ProtoId<ShaderPrototype> PaperStampShader = "PaperStamp";

    /// A scale that's applied to the text to ensure it
    /// fits in the allowed space.
    private Vector2 _textScaling = Vector2.One;

    /// Shader used to draw the stamps
    private ShaderInstance? _stampShader;

    /// Allows an additional orientation to be applied to
    /// this control.
    public float Orientation = 0.0f;

    /// Determines whether stamp noise is applied on the shader
    public bool StampNoise = true; // imp

    /// When true (signatures / manually-placed marks), the text rotates about its
    /// rect center. When false (auto-placed stamps), it uses the original
    /// top-left pivot. Set by the owning StampWidget.
    public bool PivotAboutCenter = false;

    /// <summary>
    /// Initializes a stamp label and its paper stamp shader.
    /// </summary>
    public StampLabel()
    {
        RobustXamlLoader.Load(this);

        var prototypes = IoCManager.Resolve<IPrototypeManager>();
        _stampShader = prototypes.Index(PaperStampShader).InstanceUnique();
    }

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        var desiredTextSize = base.MeasureOverride(availableSize);
        var clampedScale = Vector2.Min(availableSize / desiredTextSize, Vector2.One);
        var keepAspectRatio = MathF.Min(clampedScale.X, clampedScale.Y);
        const float shimmerReduction = 0.1f;
        _textScaling = Vector2.One * MathF.Round(keepAspectRatio / shimmerReduction) * shimmerReduction;
        return desiredTextSize;
    }

    /// <summary>
    /// Renders the stamp with its configured shader, scale, rotation, and rotation pivot.
    /// </summary>
    /// <param name="handle">The screen drawing handle used to render the label.</param>
    protected override void Draw(DrawingHandleScreen handle)
    {
        _stampShader?.SetParameter("objCoord", GlobalPosition * UIScale * new Vector2(1, -1));
        _stampShader?.SetParameter("useStampNoise", StampNoise); // imp
        handle.UseShader(_stampShader);

        if (PivotAboutCenter)
        {
            var cos = MathF.Cos(Orientation);
            var sin = MathF.Sin(Orientation);
            var half = (Vector2)PixelSize * _textScaling * 0.5f;
            var rotHalf = new Vector2(half.X * cos - half.Y * sin, half.X * sin + half.Y * cos);
            // Keeps the rect center fixed: at Orientation 0 this is GlobalPixelPosition.
            var origin = (Vector2)GlobalPixelPosition + half - rotHalf;
            handle.SetTransform(origin, Orientation, _textScaling);
        }
        else
        {
            // Original top-left pivot (pre-signature behavior).
            var offset = new Vector2(PixelPosition.X * MathF.Cos(Orientation) - PixelPosition.Y * MathF.Sin(Orientation),
                    PixelPosition.Y * MathF.Cos(Orientation) + PixelPosition.X * MathF.Sin(Orientation));
            handle.SetTransform(GlobalPixelPosition - PixelPosition + offset, Orientation, _textScaling);
        }

        base.Draw(handle);

        // Restore a sane transform+shader
        handle.SetTransform(Matrix3x2.Identity);
        handle.UseShader(null);
    }
}
