// SPDX-FileCopyrightText: 2023 Eoin Mcloughlin <helloworld@eoinrul.es>
// SPDX-FileCopyrightText: 2023 eoineoineoin <eoin.mcloughlin+gh@gmail.com>
// SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2025 Tayrtahn <tayrtahn@gmail.com>
// SPDX-FileCopyrightText: 2025 V <97265903+formlessnameless@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 maciejwalendziuk <15122746+maciejwalendziuk@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 taydeo <tay@funkystation.org>
// SPDX-FileCopyrightText: 2026 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System.Numerics;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampWidget : PanelContainer
{
    private static readonly ProtoId<FontPrototype> DefaultFont = "Default";
    private static readonly ProtoId<ShaderPrototype> PaperStampShader = "PaperStamp";

    private StyleBoxTexture? _borderTexture;
    private ShaderInstance? _stampShader;

    /// Imp edit, determines whether stamp noise is applied on the shader
    public bool StampNoise = true;

    private const int BaseSignatureFontSize = 40;

    public bool HasExplicitTransform;

    public Vector2 NormalizedPosition;

    /// <summary>
    ///     The arranged signature-ink rect within this widget (the label box),
    ///     in physical pixels relative to the widget. The widget carries fixed
    ///     margins around it, so the placement gizmo uses this to draw a box that
    ///     tightly wraps the ink at any scale.
    /// </summary>
    public Vector2 InkLabelPosPx => StampedByLabel.PixelPosition;
    public Vector2 InkLabelSizePx => StampedByLabel.PixelSize;

    public float Orientation
    {
        get => StampedByLabel.Orientation;
        set => StampedByLabel.Orientation = value;
    }

    public StampDisplayInfo StampInfo {
        set {
            // pretty much this whole thing is an imp edit

            var resCache = IoCManager.Resolve<IResourceCache>();
            var prototypes = IoCManager.Resolve<IPrototypeManager>();
            var icon = value.StampLargeIcon;
            var hasIcon = value.HasIcon;
            var scale = value.Scale ?? 1.0f;

            if (value.Position is { } pos)
            {
                HasExplicitTransform = true;
                NormalizedPosition = pos;
            }
            if (value.Rotation is { } rot)
            {
                HasExplicitTransform = true;
                Orientation = rot;
            }

            StampedByLabel.PivotAboutCenter = HasExplicitTransform;

            if (hasIcon)
            {
                var borderImage = resCache.GetResource<TextureResource>(
                        "/Textures/Interface/Paper/paper_stamp_border.svg.96dpi.png");

                if (icon != null)
                {
                    borderImage = resCache.GetResource<TextureResource>(
                            "/Textures/_Impstation/Interface/Paper/Stamps/" + icon + ".png");

                    // make stamps 50% larger to better match the original stamp sizes
                    var width = (int)(borderImage.Texture.Width * 1.5 * scale);
                    var height = (int)(borderImage.Texture.Height * 1.5 * scale);
                    SetSize = new Vector2(width, height);
                }

                _borderTexture = new StyleBoxTexture { Texture = borderImage };
                _borderTexture.SetPatchMargin(StyleBoxTexture.Margin.All, 7.0f);
                PanelOverride = _borderTexture;
            }
            else
            {
                StampNoise = false;
                StampedByLabel.StampNoise = false;
            }

            if (icon == null)
            {
                StampedByLabel.Text = value.LocalizeName ? Loc.GetString(value.StampedName) : value.StampedName;
                StampedByLabel.FontColorOverride = value.StampedColor;
                ModulateSelfOverride = value.StampedColor;

                var font = prototypes.Index(DefaultFont);
                if (value.StampFont != null && prototypes.TryIndex<FontPrototype>(value.StampFont, out var stampFont))
                    font = stampFont;

                var fontSize = (int)MathF.Max(1f, BaseSignatureFontSize * scale);
                var vectorFont = new VectorFont(resCache.GetResource<FontResource>(font.Path), fontSize);
                StampedByLabel.FontOverride = vectorFont;
            }

            _stampShader = prototypes.Index(PaperStampShader).InstanceUnique();
        }
    }

    public StampWidget()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Draws the stamp with its configured position, orientation, and visual effects.
    /// </summary>
    protected override void Draw(DrawingHandleScreen handle)
    {
        _stampShader?.SetParameter("objCoord", GlobalPosition * UIScale * new Vector2(1, -1));
        _stampShader?.SetParameter("useStampNoise", StampNoise); // imp
        handle.UseShader(_stampShader);

        if (HasExplicitTransform)
        {
            var cos = MathF.Cos(Orientation);
            var sin = MathF.Sin(Orientation);
            var half = (Vector2)PixelSize * 0.5f;
            var rotHalf = new Vector2(half.X * cos - half.Y * sin, half.X * sin + half.Y * cos);
            var origin = GlobalPosition * UIScale + half - rotHalf;
            handle.SetTransform(origin, Orientation, Vector2.One);
        }
        else
        {
            // Auto-placed stamps: original top-left pivot (byte-identical to the
            // pre-signature behavior).
            handle.SetTransform(GlobalPosition * UIScale, Orientation, Vector2.One);
        }

        base.Draw(handle);

        // Restore a sane transform+shader
        handle.SetTransform(Matrix3x2.Identity);
        handle.UseShader(null);
    }
}
