// SPDX-FileCopyrightText: 2023 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampCollection : Container
{
    private List<StampWidget> _stamps = new();

    /// Seed for random number generator to place stamps deterministically
    public int PlacementSeed;

    public StampCollection()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Remove any stamps from the page
    /// </summary>
    public void RemoveStamps()
    {
        _stamps.Clear();
        InvalidateArrange();
    }

    /// <summary>
    /// Adds a stamp to the display; will perform
    /// automatic layout.
    /// </summary>
    public void AddStamp(StampWidget s)
    {
        _stamps.Add(s);
        AddChild(s);
    }

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        var random = new RobustRandom();
        random.SetSeed(PlacementSeed);
        var r = (finalSize * 0.5f).Length();
        var dtheta = -MathHelper.DegreesToRadians(90);
        var theta0 = random.Next(0, 3) * dtheta;
        var thisCenter = PixelSizeBox.TopLeft + finalSize * UIScale * new Vector2(0.5f, 0.75f);

        var controlBox = new UIBox2(PixelSizeBox.TopLeft, PixelSizeBox.TopLeft + finalSize * UIScale);
        var autoIndex = 0;
        for (var i = 0; i < _stamps.Count; i++)
        {
            var stamp = _stamps[i];
            Vector2 childCenter;
            float stampOrientation;

            if (stamp.HasExplicitTransform)
            {
                stampOrientation = stamp.Orientation;
                childCenter = PixelSizeBox.TopLeft + finalSize * UIScale * stamp.NormalizedPosition;
            }
            else
            {
                stampOrientation = MathHelper.DegreesToRadians((random.NextFloat() - 0.5f) * 10.0f);
                stamp.Orientation = stampOrientation;

                var theta = theta0 + dtheta * 0.5f + dtheta * autoIndex + (autoIndex > 4 ? MathF.Log(1 + autoIndex / 4) * dtheta : 0); // There is probably a better way to lay these out, to minimize overlaps
                childCenter = thisCenter;
                if (autoIndex > 0)
                {
                    childCenter += new Vector2(MathF.Cos(theta), MathF.Sin(theta)) * r * UIScale;
                }
                autoIndex++;
            }

            var childHeLocal = stamp.DesiredPixelSize * 0.5f;
            var c = childHeLocal * MathF.Abs(MathF.Cos(stampOrientation));
            var s = childHeLocal * MathF.Abs(MathF.Sin(stampOrientation));
            var childHePage = new Vector2(c.X + s.Y, s.X + c.Y);
            var clampedCenter = Clamp(Shrink(controlBox, childHePage), childCenter);
            var finalPosition = clampedCenter - childHePage;
            var finalPositionAsInt = new Vector2i((int)finalPosition.X, (int)finalPosition.Y);
            stamp.ArrangePixel(new UIBox2i(finalPositionAsInt, finalPositionAsInt + stamp.DesiredPixelSize));
        }

        return finalSize;
    }

    /// <summary>
    /// Shrink a UIBox2 by a half extents, moving both the top-left and
    /// bottom-right closer together.
    /// </summary>
    private UIBox2 Shrink(UIBox2 box, Vector2 shrinkHe)
    {
        return new UIBox2(box.TopLeft + shrinkHe, box.BottomRight - shrinkHe);
    }

    /// <summary>
    /// Returns the input vector clamped to be within the UIBox
    /// </summary>
    private Vector2 Clamp(UIBox2 box, Vector2 point)
    {
        return Vector2.Min(box.BottomRight, Vector2.Max(box.TopLeft, point));
    }
}

