// SPDX-FileCopyrightText: 2022 Fishfish458 <47410468+Fishfish458@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 fishfish458 <fishfish458>
// SPDX-FileCopyrightText: 2023 Artjom <artjombebenin@gmail.com>
// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 MilenVolf <63782763+MilenVolf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 KrasnoshchekovPavel <119816022+KrasnoshchekovPavel@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Krunklehorn <42424291+Krunklehorn@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Rainfey <rainfey0+github@gmail.com>
// SPDX-FileCopyrightText: 2024 Saphire Lattice <lattice@saphi.re>
// SPDX-FileCopyrightText: 2024 Thomas <87614336+Aeshus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 TsjipTsjip <19798667+TsjipTsjip@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Whisper <121047731+QuietlyWhisper@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 goet <6637097+goet@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Hannah Giovanna Dawson <karakkaraz@gmail.com>
// SPDX-FileCopyrightText: 2025 LordCarve <27449516+LordCarve@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Fruitsalad <949631+Fruitsalad@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Maciej Walendziuk <15122746+maciejwalendziuk@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 maciejwalendziuk <15122746+maciejwalendziuk@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 taydeo <tay@funkystation.org>
// SPDX-FileCopyrightText: 2026 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Shitmed.Body;
using Content.Shared._Shitmed.Medical.HealthAnalyzer;
using Content.Shared._Shitmed.Medical.Surgery.Wounds;
using Content.Shared._Shitmed.Targeting;
using Content.Shared.Atmos;
using Content.Shared.Body;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly DamageableSystem _damageable;

    public event Action<TargetBodyPart?, EntityUid>? OnBodyPartSelected;
    public event Action<HealthAnalyzerMode, EntityUid>? OnModeChanged;

    private EntityUid _spriteViewEntity;

    [ValidatePrototypeId<EntityPrototype>]
    private readonly EntProtoId _bodyView = "AlertSpriteView";

    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
    private EntityUid? _target;

    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _damageable = _entityManager.System<DamageableSystem>();

        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.RightLeg, RightLegButton },
        };

        foreach (var (part, button) in _bodyPartControls)
        {
            button.MouseFilter = MouseFilterMode.Stop;
            button.OnPressed += _ => SetActiveBodyPart(part);
        }

        ReturnButton.OnPressed += _ => ResetBodyPart();
        BodyButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Body);
        OrgansButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Organs);
        ChemicalsButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Chemicals);
    }

    public void SetActiveBodyPart(TargetBodyPart part)
    {
        if (_target is null || _entityManager.Deleted(_target.Value))
            return;

        OnBodyPartSelected?.Invoke(part, _target.Value);
    }

    public void SetMode(HealthAnalyzerMode mode)
    {
        if (_target is null || _entityManager.Deleted(_target.Value))
            return;

        OnModeChanged?.Invoke(mode, _target.Value);
    }

    public void ResetBodyPart()
    {
        if (_target is null || _entityManager.Deleted(_target.Value))
            return;

        OnBodyPartSelected?.Invoke(null, _target.Value);
    }

    public void SetActiveButtons(bool isHumanoid)
    {
        foreach (var (_, button) in _bodyPartControls)
            button.Visible = isHumanoid;
    }

    public bool TrySetupEntity(HealthAnalyzerBaseMessage msg)
    {
        _target = _entityManager.GetEntity(msg.TargetEntity);

        if (_target is null)
        {
            NoPatientDataText.Visible = true;
            return false;
        }

        SetActiveButtons(_entityManager.HasComponent<TargetingComponent>(_target.Value));

        NoPatientDataText.Visible = false;

        ScanModeLabel.Text = msg.ScanMode.HasValue
            ? msg.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = msg.ScanMode.HasValue && msg.ScanMode.Value ? Color.Green : Color.Red;

        SpriteView.SetEntity(_entityManager.HasComponent<HumanoidProfileComponent>(_target.Value)
            ? SetupIcon(msg.Body, msg.Bleeding)
            : _target.Value);
        SpriteView.Visible = msg.ScanMode.HasValue && msg.ScanMode.Value;
        PartView.Visible = SpriteView.Visible;
        NoDataTex.Visible = !SpriteView.Visible;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(_target.Value)
            ? Identity.Name(_target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(_target.Value, out var humanoid)
                ? Loc.GetString(_prototypes.Index<SpeciesPrototype>(humanoid.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        TemperatureLabel.Text = !float.IsNaN(msg.Temperature)
            ? $"{msg.Temperature - Atmospherics.T0C:F1} °C ({msg.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(msg.BloodLevel)
            ? $"{msg.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(_target.Value, out var mobState)
                ? GetStatus(mobState.CurrentState)
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        return true;
    }

    public void Populate(HealthAnalyzerBodyMessage msg)
    {
        EntityUid? part = msg.SelectedPart != null ? _entityManager.GetEntity(msg.SelectedPart.Value) : null;
        var isPart = part != null;

        if (!TrySetupEntity(msg) || _target is null)
            return;

        var damageSource = isPart ? part!.Value : _target.Value;
        var hasDamage = _entityManager.HasComponent<DamageableComponent>(damageSource);

        // Whole-body view has no single DamageableComponent that sums every limb (the mob's
        // own pool tracks whatever's dealt directly to it, not a total of its organs - see
        // BodyDamageBridgeSystem), so it's computed here by adding up every organ's damage.
        // Mobs without TargetingComponent (corgi, cat, crab) never get their damage bridged
        // to limb organs at all, so fall back to the mob's own DamageableComponent for those.
        var bodyDamage = isPart
            ? _damageable.GetAllDamage(damageSource)
            : _entityManager.HasComponent<TargetingComponent>(_target.Value)
                ? GetBodyDamage(_target.Value)
                : _damageable.GetAllDamage(_target.Value);

        ReturnButton.Visible = isPart;
        PartNameLabel.Visible = isPart;
        DamageLabelHeading.Visible = true;
        DamageLabel.Visible = true;
        DamageLabel.Text = hasDamage ? bodyDamage.GetTotal().ToString() : "0";

        if (part != null)
            PartNameLabel.Text = _entityManager.HasComponent<MetaDataComponent>(part)
                ? Identity.Name(part.Value, _entityManager)
                : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        var showAlerts = msg.Unrevivable || msg.Bleeding.Values.Any(v => v);
        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (msg.Unrevivable)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300,
            });

        if (hasDamage)
        {
            var damageSortedGroups = (isPart ? _damageable.GetDamagePerGroup(damageSource) : bodyDamage.GetDamagePerGroup(_prototypes))
                .OrderByDescending(damage => damage.Value)
                .ToDictionary(x => x.Key, x => x.Value);
            var damagePerType = bodyDamage.DamageDict;
            DrawDiagnosticGroups(damageSortedGroups, damagePerType);
        }
        else
        {
            GroupsContainer.RemoveAllChildren();
        }

        ConditionsListContainer.RemoveAllChildren();

        TargetBodyPart? selectedBodyPart = null;
        if (isPart
            && _entityManager.TryGetComponent<OrganComponent>(part!.Value, out var organComp)
            && organComp.Category is { } category
            && LimbTargetMap.TryGetTarget(category, out var resolvedPart))
            selectedBodyPart = resolvedPart;

        foreach (var (bodyPart, isUnfinished) in msg.UnfinishedSurgery)
        {
            if (!isUnfinished || isPart && bodyPart != selectedBodyPart)
                continue;

            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString($"condition-body-unfinished-surgery-{bodyPart}", ("entity", Identity.Name(_target.Value, _entityManager))),
                Margin = new Thickness(0, 4),
            });
        }

        if (msg.Unrevivable)
            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("condition-body-unrevivable", ("entity", Identity.Name(_target.Value, _entityManager))),
                Margin = new Thickness(0, 4),
            });

        foreach (var (bodyPart, isBleeding) in msg.Bleeding)
        {
            if (!isBleeding || isPart && bodyPart != selectedBodyPart)
                continue;

            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString($"condition-body-bleeding-{bodyPart}", ("entity", Identity.Name(_target.Value, _entityManager))),
                Margin = new Thickness(0, 4),
            });
        }

        if (msg.SystemicBleeding)
            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("condition-body-bleeding-systemic", ("entity", Identity.Name(_target.Value, _entityManager))),
                Margin = new Thickness(0, 4),
            });

        foreach (var (bodyPart, hasTourniquet) in msg.Tourniqueted)
        {
            if (!hasTourniquet || isPart && bodyPart != selectedBodyPart)
                continue;

            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString($"condition-body-tourniquet-{bodyPart}", ("entity", Identity.Name(_target.Value, _entityManager))),
                Margin = new Thickness(0, 4),
            });
        }

        foreach (var (woundableEnt, traumas) in msg.Traumas)
        {
            var woundable = _entityManager.GetEntity(woundableEnt);

            if (isPart && woundable != part
                || !TryGetEntityName(woundable, out var woundableName))
                continue;

            var shownTraumas = new HashSet<(string TraumaType, string? SeverityString)>();
            foreach (var trauma in traumas)
            {
                if (!shownTraumas.Add((trauma.TraumaType, trauma.SeverityString)))
                    continue;

                var locString = trauma.SeverityString != null
                    ? Loc.GetString($"condition-body-trauma-{trauma.TraumaType}-{trauma.SeverityString}", ("woundable", woundableName))
                    : Loc.GetString($"condition-body-trauma-{trauma.TraumaType}", ("woundable", woundableName));

                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = locString,
                    Margin = new Thickness(0, 4),
                });
            }
        }

        if (!isPart)
        {
            foreach (var missingCategory in msg.MissingOrgans)
            {
                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString($"condition-organ-missing-{missingCategory}", ("entity", Identity.Name(_target.Value, _entityManager))),
                    Margin = new Thickness(0, 4),
                });
            }
        }

        if (ConditionsListContainer.ChildCount == 0)
            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("condition-none"),
                Margin = new Thickness(0, 4),
            });
    }

    private DamageSpecifier GetBodyDamage(EntityUid target)
    {
        var total = new DamageSpecifier();

        if (!_entityManager.TryGetComponent<BodyComponent>(target, out var body) || body.Organs is null)
            return total;

        foreach (var organ in body.Organs.ContainedEntities)
        {
            if (_entityManager.HasComponent<DamageableComponent>(organ))
                total += _damageable.GetAllDamage(organ);
        }

        return total;
    }

    public void Populate(HealthAnalyzerOrgansMessage msg)
    {
        if (!TrySetupEntity(msg))
            return;

        ReturnButton.Visible = false;
        PartNameLabel.Visible = false;
        DamageLabelHeading.Visible = false;
        DamageLabel.Visible = false;

        ConditionsListContainer.RemoveAllChildren();
        GroupsContainer.RemoveAllChildren();

        foreach (var (organ, data) in msg.Organs)
        {
            var organEnt = _entityManager.GetEntity(organ);

            if (!TryGetEntityName(organEnt, out var organName) || data.IntegrityCap == 0)
                continue;

            DrawOrganDiagnostics(organEnt, organName, data.Integrity / data.IntegrityCap * 100);

            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString($"condition-organ-damage-{data.Severity}", ("organ", organName)),
                Margin = new Thickness(0, 4),
            });
        }

        if (_target is not null)
        {
            foreach (var category in msg.MissingOrgans)
            {
                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString($"condition-organ-missing-{category}", ("entity", Identity.Name(_target.Value, _entityManager))),
                    Margin = new Thickness(0, 4),
                });
            }
        }

        if (ConditionsListContainer.ChildCount == 0)
            ConditionsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("condition-none"),
                Margin = new Thickness(0, 4),
            });
    }

    public void Populate(HealthAnalyzerChemicalsMessage msg)
    {
        if (!TrySetupEntity(msg))
            return;

        ReturnButton.Visible = false;
        PartNameLabel.Visible = false;
        DamageLabelHeading.Visible = false;
        DamageLabel.Visible = false;

        ConditionsListContainer.RemoveAllChildren();
        GroupsContainer.RemoveAllChildren();

        DrawSolutionDiagnostics(msg.Solutions);

        ConditionsListContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("condition-none"),
            Margin = new Thickness(0, 4),
        });
    }

    private bool TryGetEntityName(NetEntity ent, out string name)
    {
        name = Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        var targetedEnt = _entityManager.GetEntity(ent);

        if (!_entityManager.HasComponent<MetaDataComponent>(targetedEnt))
            return false;

        name = Identity.Name(targetedEnt, _entityManager);
        return true;
    }

    private bool TryGetEntityName(EntityUid ent, out string name)
    {
        name = Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        if (!_entityManager.HasComponent<MetaDataComponent>(ent))
            return false;

        name = Identity.Name(ent, _entityManager);
        return true;
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void DrawDiagnosticGroups(
        Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        foreach (var (damageGroupId, damageAmount) in groups)
        {
            if (damageAmount == 0)
                continue;

            var groupTitleText = Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount));

            var groupContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Begin,
                Orientation = BoxContainer.LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId.Id));
            GroupsContainer.AddChild(groupContainer);

            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", typeAmount));

                groupContainer.AddChild(CreateDiagnosticItemLabel(damageString.Insert(0, " · ")));
            }
        }
    }

    private void DrawOrganDiagnostics(EntityUid ent, string name, FixedPoint2 percentRemaining)
    {
        var groupTitleText = Loc.GetString(
            "group-organ-status",
            ("organ", name),
            ("capacity", percentRemaining));

        var groupContainer = new BoxContainer
        {
            Align = BoxContainer.AlignMode.Begin,
            Orientation = BoxContainer.LayoutOrientation.Vertical,
        };

        groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, ent));
        GroupsContainer.AddChild(groupContainer);
    }

    private void DrawSolutionDiagnostics(Dictionary<NetEntity, NamedSolution> solutions)
    {
        foreach (var (ent, data) in solutions)
        {
            var groupTitleText = Loc.GetString(
                "group-solution-name",
                ("solution", data.Name));

            var groupContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Begin,
                Orientation = BoxContainer.LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, "metaphysical"));
            GroupsContainer.AddChild(groupContainer);

            foreach (var reagent in data.Solution.Contents)
            {
                if (reagent.Quantity == 0)
                    continue;

                var reagentName = Loc.GetString("chem-master-window-unknown-reagent-text");
                if (_prototypes.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto))
                    reagentName = proto.LocalizedName;

                var reagentString = Loc.GetString(
                    "group-solution-contents",
                    ("reagent", reagentName),
                    ("quantity", reagent.Quantity));

                groupContainer.AddChild(CreateDiagnosticItemLabel(reagentString.Insert(0, " · ")));
            }
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out _))
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label { Text = text };
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower()),
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));
        return rootContainer;
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, EntityUid ent)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };

        var spriteView = new SpriteView
        {
            SetSize = new Vector2(30, 30),
            OverrideDirection = Direction.South,
        };
        spriteView.SetEntity(ent);
        rootContainer.AddChild(spriteView);

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));
        return rootContainer;
    }

    /// <summary>
    /// Sets up the body doll using AlertSpriteView, layering one Status RSI state per limb.
    /// </summary>
    private EntityUid? SetupIcon(Dictionary<TargetBodyPart, WoundableSeverity>? body,
        Dictionary<TargetBodyPart, bool> bleeding)
    {
        if (body is null)
            return null;

        if (!_entityManager.Deleted(_spriteViewEntity))
            _entityManager.QueueDeleteEntity(_spriteViewEntity);

        _spriteViewEntity = _entityManager.Spawn(_bodyView);

        if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
            return null;

        var layer = 0;
        foreach (var (bodyPart, severity) in body)
        {
            var enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
            var enumValue = (int) severity;
            var baseRsiPath = new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi");
            var rsi = new SpriteSpecifier.Rsi(baseRsiPath, $"{enumName.ToLowerInvariant()}_{enumValue}");
            CreateOrAddToLayer(sprite, rsi, layer);
            layer++;

            if (bleeding.TryGetValue(bodyPart, out var isBleeding) && isBleeding)
            {
                var bleedRsi = new SpriteSpecifier.Rsi(baseRsiPath, $"{enumName.ToLowerInvariant()}_bleed");
                CreateOrAddToLayer(sprite, bleedRsi, layer);
                layer++;
            }
        }

        return _spriteViewEntity;
    }

    private void CreateOrAddToLayer(SpriteComponent sprite, SpriteSpecifier rsi, int layer)
    {
        if (!sprite.TryGetLayer(layer, out _))
            sprite.AddLayer(_spriteSystem.Frame0(rsi));
        else
            sprite.LayerSetTexture(layer, _spriteSystem.Frame0(rsi));

        sprite.LayerSetScale(layer, new Vector2(3f, 3f));
    }
}
