- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 1h

- type: jobRequirementOverride
  id: Zeroed
  jobs:
    InternalAffairsAgent:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10800 # 3 hours
    Magistrate:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs
    - !type:DepartmentTimeRequirement
      department: CentralCommand
      time: 18000 #5 hrs
    NanotrasenRepresentative:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 #20 hrs
    - !type:DepartmentTimeRequirement
      department: CentralCommand
      time: 18000 #5 hrs
