using Content.Client.Administration.Managers;
using Content.Client.UserInterface.Controls;
using Content.Shared._Polonium.CallablePhone;
using Content.Shared.Administration;
using Content.Shared.Ghost.Components;
using Content.Shared.Telephone;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Polonium.CallablePhone;

[GenerateTypedNameReferences]
public sealed partial class CallablePhoneWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IClientAdminManager _admin = default!;
    [Dependency] private IPlayerManager _player = default!;

    private SharedTelephoneSystem _telephone = default!;
    private bool _canTeleport;
    private bool _adminHooked;

    private EntityUid? _owner;
    private NetEntity? _selectedContact;
    private TelephoneState _currentState;
    private TelephoneState _previousState;
    private TimeSpan _buttonUnlockTime;
    private float _updateTimer;
    private const float UpdateTime = 0.25f;
    private readonly TimeSpan _buttonUnlockDelay = TimeSpan.FromSeconds(0.5f);

    public event Action<NetEntity>? CallPressed;
    public event Action? AnswerPressed;
    public event Action? HangUpPressed;
    public event Action<NetEntity>? TeleportPressed;

    public CallablePhoneWindow()
    {
        RobustXamlLoader.Load(this);

        AnswerCallButton.OnPressed += _ => AnswerPressed?.Invoke();
        EndCallButton.OnPressed += _ => HangUpPressed?.Invoke();
        CallButton.OnPressed += _ => OnCallPressed();

        AnswerCallButton.AddStyleClass("ButtonAccept");
        EndCallButton.AddStyleClass("Caution");

        ContactListPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(47, 47, 59) * Color.DarkGray,
            BorderColor = new Color(82, 82, 82),
            BorderThickness = new Thickness(2),
        };

        ContactListHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(82, 82, 82),
        };

        SubtitleText.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("callable-phone-window-subtitle")));
    }

    public void InitializeDependencies(IDependencyCollection dependencies)
    {
        dependencies.InjectDependencies(this);

        _telephone = _entManager.System<SharedTelephoneSystem>();
        _buttonUnlockTime = _timing.CurTime + _buttonUnlockDelay;

        if (!_adminHooked)
        {
            _admin.AdminStatusUpdated += OnAdminStatusUpdated;
            _adminHooked = true;
        }

        _canTeleport = _admin.HasFlag(AdminFlags.Admin);
    }

    private void OnAdminStatusUpdated()
    {
        _canTeleport = _admin.HasFlag(AdminFlags.Admin);
        UpdateAppearance();
    }

    private bool IsLocalGhost()
    {
        var local = _player.LocalEntity;
        return local != null && _entManager.HasComponent<GhostComponent>(local.Value);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing || !_adminHooked)
            return;

        _admin.AdminStatusUpdated -= OnAdminStatusUpdated;
        
        _adminHooked = false;
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void UpdateState(Dictionary<NetEntity, string> phones)
    {
        if (_owner == null || !_entManager.TryGetComponent<TelephoneComponent>(_owner.Value, out var telephone))
            return;

        var lastCallerId = telephone.LastCallerId;

        var callerId = _telephone.GetFormattedCallerIdForEntity(
            lastCallerId?.CallerId,
            lastCallerId?.CallerJob,
            Color.LightGray,
            "Default",
            11);

        var deviceId = _telephone.GetFormattedDeviceIdForEntity(
            lastCallerId?.DeviceId,
            Color.LightGray,
            "Default",
            11);

        CallerIdText.SetMessage(FormattedMessage.FromMarkupOrThrow(callerId));
        DeviceIdText.SetMessage(FormattedMessage.FromMarkupOrThrow(deviceId));

        var phoneArray = phones.ToArray();
        Array.Sort(phoneArray, (a, b) => string.Compare(a.Value, b.Value, StringComparison.CurrentCultureIgnoreCase));

        while (ContactsList.ChildCount > phoneArray.Length)
            ContactsList.RemoveChild(ContactsList.GetChild(ContactsList.ChildCount - 1));

        for (var i = 0; i < phoneArray.Length; i++)
        {
            var (netEntity, label) = phoneArray[i];

            if (i >= ContactsList.ChildCount)
            {
                var button = new PhoneContactButton();
                button.ContactPressed += SelectContact;
                button.TeleportPressed += OnTeleportPressed;
                ContactsList.AddChild(button);
            }

            if (ContactsList.GetChild(i) is PhoneContactButton contactButton)
            {
                contactButton.UpdateValues(netEntity, label, _canTeleport);
                contactButton.Pressed = _selectedContact == netEntity;
            }
        }

        if (_selectedContact != null && !phones.ContainsKey(_selectedContact.Value))
            _selectedContact = null;

        UpdateAppearance();
    }

    private void SelectContact(NetEntity netEntity)
    {
        _selectedContact = netEntity;

        foreach (var child in ContactsList.Children)
        {
            if (child is PhoneContactButton button)
                button.Pressed = button.NetEntity == netEntity;
        }

        UpdateAppearance();
    }

    private void OnCallPressed()
    {
        if (_selectedContact == null)
            return;

        CallPressed?.Invoke(_selectedContact.Value);
    }

    private void OnTeleportPressed(NetEntity netEntity)
    {
        if (!_canTeleport || !IsLocalGhost())
            return;

        TeleportPressed?.Invoke(netEntity);
    }

    private void UpdateAppearance()
    {
        if (_owner == null || !_entManager.TryGetComponent<TelephoneComponent>(_owner.Value, out var telephone))
            return;

        if (_currentState != telephone.CurrentState)
        {
            _previousState = _currentState;
            _currentState = telephone.CurrentState;
            _buttonUnlockTime = _timing.CurTime + _buttonUnlockDelay;
        }

        var lockButtons = _timing.CurTime < _buttonUnlockTime;
        var inCall = _currentState != TelephoneState.Idle;

        ActiveCallControlsContainer.Visible = inCall;
        CallPlacementControlsContainer.Visible = !inCall;
        CallerIdContainer.Visible = _currentState == TelephoneState.Ringing;

        FetchingContactsContainer.Visible = ContactsList.ChildCount == 0;

        foreach (var child in ContactsList.Children)
        {
            if (child is not PhoneContactButton contactButton)
                continue;

            var passesFilter = string.IsNullOrEmpty(SearchLineEdit.Text) ||
                               contactButton.Text?.Contains(SearchLineEdit.Text, StringComparison.CurrentCultureIgnoreCase) == true;

            contactButton.Visible = passesFilter;
            contactButton.ShowTeleport = _canTeleport;
            contactButton.ContactDisabled = inCall || lockButtons;
            contactButton.TeleportDisabled = inCall || lockButtons || !IsLocalGhost();
        }

        switch (_currentState)
        {
            case TelephoneState.Idle:
                CallStatusText.Text = Loc.GetString("holopad-window-no-calls-in-progress");
                break;
            case TelephoneState.Calling:
                CallStatusText.Text = Loc.GetString("holopad-window-outgoing-call");
                break;
            case TelephoneState.Ringing:
                CallStatusText.Text = Loc.GetString("holopad-window-incoming-call");
                break;
            case TelephoneState.InCall:
                CallStatusText.Text = Loc.GetString("holopad-window-call-in-progress");
                break;
            case TelephoneState.EndingCall:
                CallStatusText.Text = _previousState == TelephoneState.Calling || _previousState == TelephoneState.Idle
                    ? Loc.GetString("holopad-window-call-rejected")
                    : Loc.GetString("holopad-window-call-ending");
                break;
        }

        AnswerCallButton.Disabled = _currentState != TelephoneState.Ringing || lockButtons;
        EndCallButton.Disabled = _currentState == TelephoneState.Idle || _currentState == TelephoneState.EndingCall || lockButtons;
        CallButton.Disabled = _selectedContact == null || inCall || lockButtons;
        AnswerCallButton.Visible = _currentState == TelephoneState.Ringing;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer += args.DeltaSeconds;
        if (_updateTimer >= UpdateTime)
        {
            _updateTimer -= UpdateTime;
            UpdateAppearance();
        }
    }

    private sealed class PhoneContactButton : BoxContainer
    {
        public NetEntity NetEntity;

        public string? Text => _contactButton.Text;

        public bool Pressed
        {
            get => _contactButton.Pressed;
            set => _contactButton.Pressed = value;
        }

        public bool ContactDisabled
        {
            set => _contactButton.Disabled = value;
        }

        public bool ShowTeleport
        {
            get => _teleportButton.Visible;
            set => _teleportButton.Visible = value;
        }

        public bool TeleportDisabled
        {
            set => _teleportButton.Disabled = value;
        }

        public event Action<NetEntity>? ContactPressed;
        public event Action<NetEntity>? TeleportPressed;

        private readonly Button _contactButton;
        private readonly Button _teleportButton;

        public PhoneContactButton()
        {
            Orientation = LayoutOrientation.Horizontal;
            HorizontalExpand = true;
            Margin = new Thickness(0f, 1f, 0f, 1f);
            SeparationOverride = 4;
            ReservesSpace = false;

            _contactButton = new Button
            {
                HorizontalExpand = true,
                SetHeight = 32,
                ToggleMode = true,
            };
            _contactButton.OnPressed += _ => ContactPressed?.Invoke(NetEntity);

            _teleportButton = new Button
            {
                Text = Loc.GetString("callable-phone-window-teleport"),
                ToolTip = Loc.GetString("callable-phone-window-teleport-tooltip"),
                SetHeight = 32,
                MinWidth = 40,
                Visible = false,
            };
            _teleportButton.OnPressed += _ => TeleportPressed?.Invoke(NetEntity);

            AddChild(_contactButton);
            AddChild(_teleportButton);
        }

        public void UpdateValues(NetEntity netEntity, string label, bool showTeleport)
        {
            NetEntity = netEntity;
            _contactButton.Text = Loc.GetString("holopad-window-contact-label", ("label", label));
            ShowTeleport = showTeleport;
        }
    }
}
