// SPDX-FileCopyrightText: 2026 nikitosych <174215049+nikitosych@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared._Polonium.BluespaceStrike;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.OptionButton;

namespace Content.Client._Polonium.BluespaceStrike;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class BluespaceStrikeWindow : DefaultWindow
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IEntityManager _entMan = default!;

    private readonly SharedMapSystem _mapSystem;
    private readonly SharedTransformSystem _transform;

    private readonly BluespaceStrikeEui _eui;
    private List<MapId> _mapData = new();
    private bool _pausePreview;

    public BluespaceStrikeWindow(BluespaceStrikeEui eui)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _mapSystem = _entMan.System<SharedMapSystem>();
        _transform = _entMan.System<TransformSystem>();
        _eui = eui;

        MapOptions.OnItemSelected += MapSelected;
        Recentre.OnPressed += _ => SetLocation();
        Confirm.OnPressed += SubmitButtonOnOnPressed;

        Preview.OnToggled += _ => UpdatePreview();
        MapX.OnValueChanged += _ => UpdatePreview();
        MapY.OnValueChanged += _ => UpdatePreview();
        Radius.OnValueChanged += _ => UpdatePreview();
    }

    public void SetEpsilonWarning(bool isEpsilon)
    {
        EpsilonWarning.Visible = !isEpsilon;
    }

    private void MapSelected(ItemSelectedEventArgs args)
    {
        MapOptions.SelectId(args.Id);
        UpdatePreview();
    }

    protected override void EnteredTree()
    {
        SetLocation();
    }

    private void UpdateMapOptions()
    {
        _mapData.Clear();
        MapOptions.Clear();
        foreach (var map in _mapSystem.GetAllMapIds())
        {
            _mapData.Add(map);
            MapOptions.AddItem(map.ToString());
        }
    }

    private void SetLocation()
    {
        UpdateMapOptions();

        if (!_entMan.TryGetComponent(_playerManager.LocalEntity, out TransformComponent? transform))
            return;

        _pausePreview = true;
        MapOptions.Select(_mapData.IndexOf(transform.MapID));
        (MapX.Value, MapY.Value) = _transform.GetMapCoordinates(_playerManager.LocalEntity!.Value, xform: transform).Position;
        _pausePreview = false;

        UpdatePreview();
    }

    private void UpdatePreview()
    {
        if (_pausePreview)
            return;

        if (!Preview.Pressed)
        {
            _eui.ClearOverlay();
            return;
        }

        if (_mapData.Count == 0)
            return;

        var coords = new MapCoordinates(new Vector2(MapX.Value, MapY.Value), _mapData[MapOptions.SelectedId]);
        _eui.RequestPreviewData(coords, MathF.Max(0.1f, Radius.Value));
    }

    private void SubmitButtonOnOnPressed(ButtonEventArgs args)
    {
        Preview.Pressed = false;
        _eui.ClearOverlay();

        if (_mapData.Count == 0)
            return;

        var delay = Math.Clamp(Delay.Value,
            BluespaceStrikeComponent.MinDelaySeconds,
            BluespaceStrikeComponent.MaxDelaySeconds);
        Delay.Value = delay;

        var radius = MathF.Max(0.1f, Radius.Value);
        var coords = new MapCoordinates(new Vector2(MapX.Value, MapY.Value), _mapData[MapOptions.SelectedId]);
        _eui.ConfirmStrike(coords, radius, delay, ShowMarkersAndSound.Pressed);
    }
}
