using Content.Shared._Shitmed.Medical.Surgery.Wounds;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Shitmed.UserInterface.Systems.PartStatus.Widgets;

[GenerateTypedNameReferences]
public sealed partial class PartStatusControl : UIWidget
{
    [Dependency] private IGameTiming _timing = default!;
    private readonly Dictionary<TargetBodyPart, TextureRect> _partStatusControls;
    private readonly PartStatusUIController _controller;

    public PartStatusControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<PartStatusUIController>();
        _partStatusControls = new Dictionary<TargetBodyPart, TextureRect>
        {
            { TargetBodyPart.Head, DollHead },
            { TargetBodyPart.Chest, DollTorso },
            { TargetBodyPart.LeftArm, DollLeftArm },
            { TargetBodyPart.RightArm, DollRightArm },
            { TargetBodyPart.LeftLeg, DollLeftLeg },
            { TargetBodyPart.RightLeg, DollRightLeg },
        };

        MouseFilter = MouseFilterMode.Stop;
        OnKeyBindDown += OnClicked;
    }

    public void SetTextures(Dictionary<TargetBodyPart, WoundableSeverity> state)
    {
        foreach (var (bodyPart, severity) in state)
        {
            if (!_partStatusControls.TryGetValue(bodyPart, out var control))
                continue;

            var enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart)?.ToLowerInvariant() ?? "unknown";
            var enumValue = (int) severity;
            var texture = new SpriteSpecifier.Rsi(
                new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName}.rsi"),
                $"{enumName}_{enumValue}");

            control.Texture = _controller.GetTexture(texture);
        }
    }

    private void OnClicked(GUIBoundKeyEventArgs args)
    {
        if (_timing.IsFirstTimePredicted && args.Function == EngineKeyFunctions.Use)
            _controller.GetPartStatusMessage();
    }

    public void SetVisible(bool visible) => Visible = visible;
}
