- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedicFilled # inheriting from other locker because there is no need to have different equipment for 2. Don't list contents below. - Polonium
