using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Bql;

[GenerateTypedNameReferences]
internal sealed partial class ToolshedVisualizeWindow : DefaultWindow
{
    private readonly IClientConsoleHost _console;
    private readonly ILocalizationManager _loc;

    public ToolshedVisualizeWindow(IClientConsoleHost console, ILocalizationManager loc)
    {
        _console = console;
        _loc = loc;

        RobustXamlLoader.Load(this);
    }

    public void Update((string name, NetEntity entity)[] entities)
    {
        Administration.UI.AdminEntityResultsList.Populate(ItemList, StatusLabel, entities, _console, _loc);
    }
}
