using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Bql;

[GenerateTypedNameReferences]
internal sealed partial class ToolshedVisualizeWindow : DefaultWindow
{
    private readonly IClientConsoleHost _console;
    private readonly ILocalizationManager _loc;
    private readonly IClipboardManager _clipboard;
    private readonly IResourceCache _resCache;

    public ToolshedVisualizeWindow(IClientConsoleHost console, ILocalizationManager loc, IClipboardManager clipboard, IResourceCache resCache)
    {
        _console = console;
        _loc = loc;
        _clipboard = clipboard;
        _resCache = resCache;

        RobustXamlLoader.Load(this);

        Administration.UI.AdminEntityResultsList.PopulateHeader(HeaderRow, _loc);
    }

    public void Update((string name, NetEntity entity)[] entities)
    {
        // BQL has no prototype id per row, so proto is null
        var rows = new (string name, string? proto, NetEntity entity)[entities.Length];
        for (var i = 0; i < entities.Length; i++)
            rows[i] = (entities[i].name, null, entities[i].entity);

        Administration.UI.AdminEntityResultsList.Populate(ItemList, StatusLabel, rows, _console, _loc, _clipboard, _resCache);
    }
}
