name: Build & Test Debug

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'merge_group' && !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.actor) }}

env: # Polonium: prevent dotnet from sending telemetry
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    if: >-
      !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.actor) &&
      (github.event_name != 'pull_request' || (
        !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.event.pull_request.user.login) &&
        github.event.pull_request.draft == false
      )) &&
      (github.event_name != 'push' || (
        !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.event.pusher.name) &&
        !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.event.head_commit.author.name) &&
        !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.event.head_commit.author.username) &&
        !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.event.head_commit.committer.name) &&
        !contains(fromJSON('["Polonium-bot","PJBot","github-actions[bot]","github-actions"]'), github.event.head_commit.committer.username)
      ))
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Master
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        cache: true # Polonium
        cache-dependency-path: |
          **/*.csproj
          nuget.config
          RobustToolbox/nuget.config

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration DebugOpt --no-restore /m

    - name: Run Content.Tests
      shell: pwsh
      run: dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0 NUnit.TestOutputXml="logs" NUnit.WorkDirectory="$(pwd)/test_results"

    - name: Run Content.IntegrationTests
      shell: pwsh
      run: |
        $env:DOTNET_gcServer=1
        dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed NUnit.TestOutputXml="logs" NUnit.WorkDirectory="$(pwd)/test_results"

    - name: Archive NUnit3 test results.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: nunit3-results
        path: test_results/*
        retention-days: 7
        compression-level: 9
  ci-success:
    name: Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
