name: "Labels: Approved"
on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  issues: write

jobs:
  add_label:
    # Change the repository name after you've made sure the team name is correct for your fork!
    if: ${{ (github.repository == 'polonium14/polonium-station') && (github.event.review.state == 'approved' || github.event.review.state == 'APPROVED') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_TOKEN || github.token }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['S: Zatwierdzono'],
            })
