name: Publish Changelog Only

on:
  workflow_dispatch:

jobs:
  publish-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Publish changelog (Discord)
        continue-on-error: true
        run: Tools/actions_changelogs_since_last_run.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

      - name: Publish changelog (RSS)
        continue-on-error: true
        run: Tools/actions_changelog_rss.py
        env:
          CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
